### ISSUE TITLE
ClassCastException in Lua script result processing returning List [DATAREDIS-711]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-data-redis#1285]
**[Mark Paluch](https://jira.spring.io/secure/ViewProfile.jspa?name=mp911de)** opened **[DATAREDIS-711](https://jira.spring.io/browse/DATAREDIS-711?redirect=false)** and commented

Executing a Lua script returning a `List` response fails during response processing (e.g. applying map or filter operators) with a `ClassCastException` because of single element emission instead of emitting a list.

Lettuce emits each element of the returned list as single element but the generic types between `RedisScript` and the returned `Flux` do not match:

Code to reproduce:

```java
DefaultRedisScript<List> script = new DefaultRedisScript<>();
script.setResultType(List.class);

Flux<List> flow = template.execute(script,…).map(list -> …);
```

Additionally, generics do not work well with types accepting generics, it would make sense to be able to write the following code:

```java
DefaultRedisScript<List<Integer>> script = new DefaultRedisScript<>();
script.setResultType(List.class);

Flux<List> flow = template.execute(script,…);
```

NB: `execute` requires probably a different name and `setResultType` should be declared like `<S extends T> void setResultType(Class<S> resultType)`

---

**Affects:** 2.0 GA (Kay)

**Referenced from:** pull request https://github.com/spring-projects/spring-data-redis/pull/282

**Backported to:** [2.0.1 (Kay SR1)](https://github.com/spring-projects/spring-data-redis/milestone/85?closed=1)

**Comment by Star-ho** [comment]
I appreciate your insights on preferring to emit List<T> instead of T for Lua scripting. Your reasoning about handling null values and maintaining consistency with existing generic signatures makes a lot of sense.

However, when working with Kotlin, there are some constraints due to its strict generic type system that differ from Java's flexibility with raw types. Specifically, Kotlin does not support raw types like List without specifying type parameters. This strictness is designed to enhance type safety and prevent potential runtime errors.

The Issue
In Kotlin, if you attempt to use T instead of List<T>, you'll encounter type safety issues because Kotlin requires all generic types to have their type parameters explicitly defined. For example:

kotlin
```
// This will cause a compilation error in Kotlin
fun getScript(): RedisScript<List> {
    // Implementation
}
``
Kotlin enforces that you specify the type parameter, such as List<Any> or a more specific type like List<String>. Without specifying the type, the compiler cannot ensure type safety, leading to errors.

**Comment by mp911de** [comment]
Do you think it would make sense to introduce a Kotlin extension? If so, feel free to either file a ticket or submit a pull request directly.
