### ISSUE TITLE
Big key issues in Redis Repositories

### ISSUE THREAD

**Issue by chao-chang-paypay** [spring-projects/spring-data-redis#1938]
If Redis repositories  are used, all hash keys will be stored in a set ,as is explained in the [reference guide](https://docs.spring.io/spring-data/redis/docs/2.4.2/reference/html/#redis.repositories.anatomy.insert) , 
this might introduce a big key , for the `Person` example,  the hash key is a uuid, assuming each item in the set will use 36 bytes(e.g. `19315449-cda2-4f5c-b696-9cb8018fa1f9` ) for each entity, the memory usage of the set will reach **100MB** if the size of all entries is 3 million. this might cause performance issues (resizing in rehashing , reallocating hash slots in the cluster mode) if there is massive data.
It seems that the big set is used for operations like `count` or `contains` , which are not used in some( if not most) real use cases for the Redis repositories, So I'm wondering whether we can eliminate the use of this set.
for example,  we can check whether the set is actually needed by checking the Repository Interface which the application Repository inherits, if it is `CrudRepository`([link](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/CrudRepository.html)), where there is `findAll` method, then it might indicate that keeping the set is needed, but in case  it is `Repository`([link](https://docs.spring.io/spring-data/commons/docs/current/api/org/springframework/data/repository/Repository.html)) and there are also no methods in the application repository class where the set is needed, we might be able to turn it off.

**Comment by mp911de** [comment]
Spring Data Redis tracks a few indexes for various purposes. `findAll` is the major driver behind the keyspace index.

I'd suggest implementing a `Simple…Repository` yourself along with an optimized entity persistence strategy if you want to heavily customize how to store and find Redis entities. You have access to all infrastructure components to materialize an entity from a hash and how to write an entity into a hash. Alternatively, override `RedisKeyValueAdapter.put(…)` to customize the method as you need to.

Individual control of maintenance index structures isn't intended.

Since there isn't much we can and want to, I'm closing this ticket.
