### ISSUE TITLE
@Cachable not working with Jackson2JsonRedisSerializer

### ISSUE THREAD

**Issue by tweetysat** [spring-projects/spring-data-redis#1949]
I'm using `Spring Boot 2.4.2` with

    <dependency>
	    <groupId>org.springframework.boot</groupId>
     	<artifactId>spring-boot-starter-data-redis</artifactId>
    </dependency>

In my appication I have

    package com.tuto.app1;
    import lombok.Data;
    @Data
    public class Student {
        private String firstName;
        private String lastName;
        private int age;
    }

Also

    @Bean
    public CacheManager redisCacheManager() {
        RedisSerializationContext.SerializationPair<Object> jsonSerializer =
                RedisSerializationContext.SerializationPair.fromSerializer(new new Jackson2JsonRedisSerializer<>(Object.class));
        return RedisCacheManager.RedisCacheManagerBuilder
                .fromConnectionFactory(redisConnectionFactory())
                .cacheDefaults(
                        RedisCacheConfiguration.defaultCacheConfig()
                                .entryTtl(Duration.ofDays(1))
                                .serializeValuesWith(jsonSerializer)
                )
                .build();
    }

And 

    @GetMapping("/students/{name}")
    @Cacheable(value = "student")
    public Student getStudent(@PathVariable String name) {
        Student student = new Student();
        student.setFirstName("John");
        student.setLastName(name);
        student.setAge(30);
        return student;
    }

First call to `http://.../app1/students/toto` returns

    {
    "firstName": "John",
    "lastName": "toto",
    "age": 30
    }

And in cache I have

    {"firstName":"John","lastName":"toto","age":30}

Ok, it's what I want.

BUT ... all other call to `http://.../app1/students/toto`are giving me

    class java.util.LinkedHashMap cannot be cast to class com.tuto.app1.Student (java.util.LinkedHashMap is in module java.base of loader 'bootstrap'; com.tuto.app1.Student is in unnamed module of loader org.springframework.boot.devtools.restart.classloader.RestartClassLoader @32bd421)
    java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class com.tuto.app1.Student (java.util.LinkedHashMap is in module java.base of loader 'bootstrap'; com.tuto.app1.Student is in unnamed module of loader org.springframework.boot.devtools.restart.classloader.RestartClassLoader @32bd421)

**Comment by mp911de** [comment]
Using `Jackson2JsonRedisSerializer` with `Object` uses `Object` as type hint when deserializing cache values. Since the stored JSON represents a plain object containing property values only (no type hints), the deserializer returns a `Map`. Either change the type to `Student.class` (`new new Jackson2JsonRedisSerializer<>(Student.class)`) or use a generic JSON mapper that considers type hints (`GenericJackson2JsonRedisSerializer`). Note that a generic JSON mapper may instantiate classes beyond the intended ones so having a securely configured `ObjectMapper` to avoid vulnerabilities is required if you cannot trust the Redis data.
