### ISSUE TITLE
Missing support for SWAPDB command

### ISSUE THREAD

**Issue by Tiller** [spring-projects/spring-data-redis#2121]
Hello,

I was looking for the SWAPDB command in the reactive API, but I couldn't find it. I've looked everywhere I could think of, so I'm assuming it is not implemented.

1/ can you confirm?
2/ any plan to add support for this command?
3/ is there a workaround?

Thanks

**Comment by mp911de** [comment]
We consider `SWAPDB` an administrative command that we didn't introduce due to the given complexity of supporting an additional command and the fact that you can invoke each command by obtaining the native connection (`LettuceConnection.getNativeConnection`). In general, we try to limit the command surface to commands that operate on data structures.

**Comment by Tiller** [comment]
Ok thanks for the quick answer. I switched to native Lettuce on my end. Feel free to close if you think it's not worth adding support for the command

**Comment by mp911de** [comment]
Thanks for your feedback. Closing this one without implementing it.
