### ISSUE TITLE
Can the set method set a timestamp?

### ISSUE THREAD

**Issue by xuMingHai1** [spring-projects/spring-data-redis#2205]
I want to set a timestamp for the key when adding the cache, but I find that there is only an expiration time

**Comment by mp911de** [comment]
The cache configuration only accepts a TTL (`Duration`). We do not support setting a time as that would include the local time of the client into time calculation or would require time retrieval from the Redis server. Since both approaches introduce additional overhead or dependencies to the local client time we do not allow setting the expiration timestamp.
