### ISSUE TITLE
[Urgent] Unable to connect to Microsoft Azure Redis in cluster mode

### ISSUE THREAD

**Issue by SyedAanif** [spring-projects/spring-data-redis#2255]
Hi Team,
We are trying to connect our Spring Boot application to `Microsoft Azure Redis Cache`, but getting the below mentioned error.
**Error::** `Redis connection failed; nested exception is io.lettuce.core.RedisConnectionException: Unable to connect to [rediss://********************************************@myurl.redis.cache.windows.net:6380?timeout=3s]`

**spring.cloud.version::** `2020.0.3`
**spring.boot.version::** `2.5.5`
```
Microsoft Azure Redis
Hostname:: myurl.redis.cache.windows.net
Port:: 6380
Primary access key/password:: ***********************
SSL enabled:: true
TLS:: 1.2
redisVersion:: 4.1.14
"sku": {
    "name": "Premium",
    "family": "P",
    "capacity": 1
}
Shards:: 2
```

```
pom.xml
<!-- REDIS-->
        <dependency>
            <groupId>org.springframework.data</groupId>
            <artifactId>spring-data-redis</artifactId>
            <version>2.6.1</version>
        </dependency>
        <dependency>
            <groupId>io.lettuce</groupId>
            <artifactId>lettuce-core</artifactId>
            <version>6.1.6.RELEASE</version>
        </dependency>
```

```
Redis Configuration
@Bean
    public RedisClusterConfiguration defaultRedisConfig() {
        RedisClusterConfiguration configuration = new RedisClusterConfiguration();
        configuration.addClusterNode(new RedisNode("myurl.redis.cache.windows.net",6380));
        configuration.setPassword(RedisPassword.of(primary_access_key));
        return configuration;
    }

    @Bean
    @Primary
    public RedisConnectionFactory redisConnectionFactory(RedisClusterConfiguration defaultRedisConfig) {
        ClusterTopologyRefreshOptions topologyRefreshOptions = ClusterTopologyRefreshOptions.builder()
                .enablePeriodicRefresh(Duration.ofMinutes(10L))
                .enableAllAdaptiveRefreshTriggers()
                .build();

        LettuceClientConfiguration clientConfig = LettuceClientConfiguration.builder()
                .useSsl().and()
                .commandTimeout(Duration.ofMillis(3000))
                .clientOptions(ClusterClientOptions.builder().topologyRefreshOptions(topologyRefreshOptions).build())
                .build();

        return new LettuceConnectionFactory(defaultRedisConfig, clientConfig);
    }

    @Bean
    public RedisTemplate<String, Object> redisTemplate(RedisConnectionFactory redisConnectionFactory) {
        RedisTemplate<String, Object> redisTemplate = new RedisTemplate<>();
        redisTemplate.setConnectionFactory(redisConnectionFactory);
        return redisTemplate;
    }
```

Can you point out what's going wrong here? Any kind of help would really be appreciated.

**Comment by mp911de** [comment]
Can you provide a debug log of the Lettuce connect attempt? Without additional details, we're not able to diagnose the issue.

**Comment by SyedAanif** [comment]
Thanks for the prompt reply.
I guess getting the logs wouldn't be possible because of the company policies.
But yes could you please specify on the code and query I have specified above, what could be the possible wrong adaptation?
I also saw somewhat the same issue here #1470 , this is not fully related, but the solution should be working.
Please do provide your suggestions.

**Comment by mp911de** [comment]
The config code looks fine. Closing the ticket as it is not actionable.

**Comment by ucinskij** [comment]
Hi @mp911de I'd like to give some more details as we played around with this a bit more.

By now we're pretty sure it's related to SSL. It's enough for us to expose the non-SSL port (6379) and comment out the `useSsl()` method call when building up the `LettuceClientConfiguration`. With these changes, everything seems to work fine. Otherwise we get the error that @SyedAanif has posted above.

One more detail here: we deploy the Azure Redis instance(s) by using our own Virtual Network, it's not publicly available. To connect from within our k8s cluster, we use Azure Redis' host name which is like this `my-redis.redis.cache.windows.net`. The port is obviously `6380`.

What I can see in the logs is something like this:
```
Unable to connect to [xx.xxx.104.135:15002]: No subject alternative names matching IP address xx.xxx.104.135 found
Unable to connect to [xx.xxx.104.135:15001]: No subject alternative names matching IP address xx.xxx.104.135 found
Unable to connect to [xx.xxx.104.135:15003]: No subject alternative names matching IP address xx.xxx.104.135 found
Unable to connect to [xx.xxx.104.135:15000]: No subject alternative names matching IP address xx.xxx.104.135 found
```
The IP address is the same for all the four logs and matches our VNet and subnet, that looks good. However it seems like the IP doesn't match the SSL Cert. However, the initial connection that uses the host name must be successful because the app can clearly see the nodes/shards. We have two shards and two replicas, so it seems to match.

I'm yet to turn on debug logging. As soon as I'll get my hands on those, I'll try to provide more details.

**Comment by mp911de** [comment]
This is, in any case, not a Spring issue, more related to the client. Redis Cluster addressing works using IP addresses. While Redis is introducing means to use hostnames, I expect Azure Redis is not there yet. That leaves the client with IP addresses and the client verifies the target host coordinates against the SSL certificate. 

Azure Redis leaves clients with an SSL certificate that doesn't match the addressing arrangement and your only option is bypassing the hostname check by disabling SSL verification. When using Spring Data Redis, you can do so by calling the `disablePeerVerification` method in `LettuceSslClientConfigurationBuilder`.
