### ISSUE TITLE
`error: cannot access JedisShardInfo` with spring-data-redis:2.6.4 and Jedis 4.2.3

### ISSUE THREAD

**Issue by razorree** [spring-projects/spring-data-redis#2320]
```
error: cannot access JedisShardInfo
    return new JedisConnectionFactory(connectionConfig);
           ^
  class file for redis.clients.jedis.JedisShardInfo not found
```

spring-data-redis uses removed `JedisShardInfo`, not possible to compile project with new Jedis lib.

**Comment by christophstrobl** [comment]
Due to the amount of breaking changes in Jedis 4, Spring Data Redis 2.x cannot be used with Jedis 4.x.
Jedis 4.x support will be part of Data Redis 3.0 (see: #2212).

**Comment by HengCC** [comment]
@christophstrobl  I've encountered a similar issue as well. I actually raised this concern on the Spring Boot side before. https://github.com/spring-projects/spring-boot/issues/37136 In version 2.7.15, Spring Boot includes jedis 4.x, which is causing this error to occur. I believe there are still many projects that cannot upgrade to Spring Boot 3.x. Are there any other feasible solutions to temporarily address this problem? The reason is that features like Redis search are only available in jedis 4 and later.

**Comment by christophstrobl** [comment]
@HengCC I do not think there's a reasonable way to do this given the amount of [breaking changes](https://github.com/redis/jedis/blob/master/docs/3to4.md) in Jedis 4.

**Comment by HengCC** [comment]
Thank you for your response. I'm now in the process of trying to upgrade JDK to version 17 and moving from Spring Boot 2 to 3. It's quite a massive undertaking. 

> @HengCC I do not think there's a reasonable way to do this given the amount of [breaking changes](https://github.com/redis/jedis/blob/master/docs/3to4.md) in Jedis 4.
