### ISSUE TITLE
RedisMessageListenerContainer prevents app startup on missing connection

### ISSUE THREAD

**Issue by kinglite** [spring-projects/spring-data-redis#2334]
When no Redis connection is available on Spring-Boot startup, the bean creation fails and throws an Exception that will cause the start procedure to fail and exit the application.

This is the part of the code in question:
https://github.com/spring-projects/spring-data-redis/blob/main/src/main/java/org/springframework/data/redis/listener/RedisMessageListenerContainer.java#L1169

In comparison to branch 2.6.x this was inside a try/catch (I think at least, as it seems to be a completely new implementation)

(https://stackoverflow.com/questions/72436006/spring-boot-2-7-redis-pub-sub-fails-startup-on-missing-redis-connection)

**Comment by mp911de** [comment]
While there's a bug in handling exceptions in the `initialize` method (it can escape and bypass the state handling code), it is by design to fail on `start` or `addMessageListener` (when the container is started) methods. Silently not subscribing if Redis is down would be a false promise and break expectations.
