### ISSUE TITLE
Add support for GETEX in Spring Redis Cache

### ISSUE THREAD

**Issue by danibs** [spring-projects/spring-data-redis#2351]
Hi,
in version > 2.6:
https://docs.spring.io/spring-data/data-redis/docs/current/reference/html/#new-in-2.6.0

you support [GETEX](https://redis.io/commands/getex/) command that permits (I think) to have a kind of "time to idle" like in EhCache (`ExpiryPolicyBuilder.timeToIdleExpiration`) where the key doesn't expire if someone get its value.

I updated my `pom.xml` with:
```xml
<dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-redis</artifactId>
    <version>2.7.1</version>
</dependency>
```

but in `RedisCacheConfiguration` class there is only `Duration ttl` attribute.
I found this https://dzone.com/articles/how-to-boost-redis-with-local-caching-in-java but it talks about _Redisson_ and I found in library that is possible to have **timeToLive** and **Idle**:
```java
LocalCachedMapOptions.defaults()
   .evictionPolicy(EvictionPolicy.LFU)
   .timeToLive(48, TimeUnit.MINUTES)
   .maxIdle(24, TimeUnit.MINUTES);
```

Do I miss something?
Thanks

**Comment by jxblum** [comment]
@bytestreme - Before discussing and reviewing any [changes](https://github.com/spring-projects/spring-data-redis/pull/2643) to Spring Data Redis, I want to clarify a few things.

Your (implied) recommendation is to support cache entry, idle-timeout expiration (TTI) using the Redis [GETEX](https://redis.io/commands/getex/) command (as evident in your [PR](https://github.com/spring-projects/spring-data-redis/pull/2643)) in addition to cache entry, time-to-live expiration (TTL) currently used by Spring Data Redis's [implementation](https://docs.spring.io/spring-data/redis/docs/current/reference/html/#redis:support:cache-abstraction) of Spring Framework's [Cache Abstraction](https://docs.spring.io/spring-framework/reference/integration/cache/strategies.html).

> NOTE: It is true that Spring Data Redis supports the Redis `GETEX` command via the `RedisCommands` API (specifically, `RedisStringCommands` ([Javadoc](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/connection/RedisStringCommands.html#getEx(byte%5B%5D,org.springframework.data.redis.core.types.Expiration))) when given a `RedisConnection`. The implementation is Redis (client) driver specific, using either _Jedis_ or _Lettuce_. But, both drivers ultimately invoke the Redis `GETEX` command **on the server**.

Second, I also read the DZone [article](https://dzone.com/articles/how-to-boost-redis-with-local-caching-in-java) you shared and a few things stood out to me:

1) The article is specifically focused on local, "_client-side caching_" (or "_Near Caching_"), which is a _caching pattern_ used to address application latency and reduction in system resource allocation (network/load).

2) Also, local, "_client-side caching_" as well as **cache entry idle-timeout expiration** (TTI) is only available in the PRO (aka "commercial, and paid") version  of Redisson, as highlighted in the "_Conclusion_":

> "_Redisson includes a variety of options for Java developers to perform local caching in Redis: Maps, Spring Cache, Hibernate Cache, and JCache. Note that the last three options — Spring Cache, Hibernate Cache, and JCache — **are only available for Redisson PRO users**._"

As it turns out, local, client-side caching is not a trivial problem. 1 of the most challenging tasks, especially in a distributed topology, is consistency, and not just between server nodes in a cluster (e.g. using replication for HA), but also consistency between client(s) and server(s).

Redis makes no guarantees of consistency on the server-side primarily because replica updates are asynchronous. This problem is further compounded by client-side caching, and is typically only used when data updates are infrequent (i.e. reads far exceed writes) or strong consistency is not a major concern.

So, it is not surprising that these features are only available in the PRO version, or rather commercial/paid option. See the comparisons between the OSS and PRO versions, [here](https://redisson.pro/).

Next up, "_cache entry, idle-timeout expiration_ (TTI)"...

**Comment by jxblum** [comment]
Regarding your specific (implied) ask for **cache entry, idle-timeout expiration** (TTI), Redis's [GETEX](https://redis.io/commands/getex/) command is NOT an implementation of TTI. Rather, it is a per cache entry (key-based) time-to-live expiration (TTL) policy on `GET` when given a "key". This is even evident in the "Examples" of the Redis documentation on the `GETEX` command.

By way of example, if you were to execute these series of commands:

```txt
$ SET sessionId 123
$ GETEX sessionId EX 600   // Session timeout after 5 minutes
"123"
// Wait 4 minutes
$ GET sessionId
"123"
// Wait 1 minute
$ GET sessionId
(nil)
```

That is, the simple act of "reading" the key does NOT reset the expiration timeout (back to 5 minutes) upon (read) access.

Although, if each subsequent `GET` after the initial `GETEX` is replaced by a call to `GETEX`, then, in essence, you do achieve a cheap, half-baked form of cache entry idle-timeout expiration (TTI), which I suppose is OK, but really does not properly take into account the multiple access patterns used by the application (e.g. via Templating or SD Repositories). So,  the responsibility falls to the application developer to ensure whatever object (not just "sessions") that are set to expire, expire when they are logically no longer in use, and not just when caching.

**Comment by jxblum** [comment]
There is another Redis command [OBJECT IDLETIME](https://redis.io/commands/object-idletime/) that properly assesses whether a particular key is "idle".

By way of example:

```txt
127.0.0.1:6379> GET sessionId
(nil)
127.0.0.1:6379> SET sessionId ABC
OK
127.0.0.1:6379> GET sessionId
"ABC"
127.0.0.1:6379> OBJECT IDLETIME sessionId
(integer) 30
127.0.0.1:6379> GETEX sessionId EX 30
"ABC"
127.0.0.1:6379> OBJECT IDLETIME sessionId
(integer) 17
127.0.0.1:6379> GET sessionId
"ABC"
127.0.0.1:6379> OBJECT IDLETIME sessionId
(integer) 2
127.0.0.1:6379> GET sessionId
(nil)
127.0.0.1:6379> OBJECT IDLETIME sessionId
(nil)
```

I performed these commands within a span of only a few seconds apart. Still, the object (ABC) with key (sessionId) expired after 30 seconds (set with `GETEX sessionId EX 60`), but using `OBJECT IDLETIME`, it accurately reflected each access, using only `GET`.

Therefore, without some "external" TTI expiration monitor (perhaps using `OBJECT IDLETIME`) then the application must consistently using [GETEX](https://redis.io/commands/getex/), or even [SET](https://redis.io/commands/set/) with expiration options **consistently**.

**Comment by jxblum** [comment]
See PR #2649.
