### ISSUE TITLE
RedisTemplate fields valueOps, listOps, setOps and so on are final; Can they be changed to non-final with getters/setters, or provide a way to wrap those operations

### ISSUE THREAD

**Issue by radut** [spring-projects/spring-data-redis#2516]
Hi,
I was wondering why valueOps and other similar fields are final in RedisTemplate. 

I'm currently looking into attaching to every  operation a wrapper. In spring world there could be a interceptor for new beans which will replace for example valueOps with newValueOps which does some logging + real valueOps.

Would be great if we could have a way to wrap the real ValueOperations, ListOperations and so on, or just be able to replace them with custom code + call to real *Operations.

See WebClient-filter / RestTemplate-interceptor.

**Comment by jxblum** [comment]
Hi @radut -

In general, `private [final]` **fields** declared in any POJO, and proper _JavaBean_, should never be accessed directly in this way since it would violate encapsulation, and possibly change the invariants of the object. For instance, if the _Spring [Data [Redis]] framework_ were to provide (additional) wrappers (or interceptors) around these operational interfaces, depending on the context, then you could possibly and inadvertently circumvent this decoration.

`RedisTemplate`, like other templates and infrastructure components in _Spring [Data]_, may delegate some of its responsibilities or operations to utility/helper classes. This is an implementation detail that users should not generally have to concern themselves with to use the template correctly. Doing so would be akin to accessing the `transient Object[] elementData` array field in the `ArrayList`, `List` implementation. If the implementation details of the field ever changes, then it would very likely break your code.

Fortunately, `RedisTemplate` provides an accessor method already, the `opsForValue()` method ([Javadoc](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/core/RedisTemplate.html#opsForValue()); [source](https://github.com/spring-projects/spring-data-redis/blob/3.0.2/src/main/java/org/springframework/data/redis/core/RedisTemplate.java#L1040-L1043)) returning the `ValueOperations` object referenced in the `private final` field of the template, [here](https://github.com/spring-projects/spring-data-redis/blob/3.0.2/src/main/java/org/springframework/data/redis/core/RedisTemplate.java#L112). Then, all that is required is for the `RedisTemplate` to refer to `ValueOperations` object using the `opsForValue()` method rather than the `valueOps` field , which it [does](https://github.com/spring-projects/spring-data-redis/blob/3.0.2/src/main/java/org/springframework/data/redis/core/RedisTemplate.java#L1037). This should be true of all utility/helper operation interfaces used and delegated to by the `RedisTemplate`.

Now it becomes a simple matter to wrap and decorate the `RedisTemplate` bean as necessary since the `public` methods return configured and initialized references to the operational interfaces that make up the template's functionality as part of its contract.

By way of example:

```java
abstract class DelegateValueOperations<K, V> {

  private final ValueOperations<K, V> delegate;

  DecoratedValueOperations(@NonNull ValueOperations<K, V> valueOperations) {
    Assert.notNull(valueOperations, "ValueOperations delegate must not be null");
    this.delegate;
  }

  protected @NonNull ValueOperations<K, V> getValueOperations() {
    return this.delegate;
  }

  @Override
  public void set(K key, V value) {
    return getValueOperations().set(key, value):
  }

  @Override
  public V get(Object key) {
    return getValueOperations.get(key);
  }

  // other ValueOperations interface methods implemented with simple delegation, by default

}
```

Then...

```java
class WrapperValueOperations<K, V> extends DelegateValueOperations<K, V> {

  WrapperValueOperations(@NonNull ValueOperations<K, V> valueOperations) {
    super(valueOperations);
  }

  @Override
  public V get(Object key) {

    // perhaps, capture some metrics, such as timing using Micrometer, log some details, 
    // or perform additional validation on the key

    V value = super.get(key);

    // perform any post get(..) operation activity

    return value;
  }
}
```

And, finally...

```java
@Configuration
class MyApplicationRedisConfiguration {

  @Bean
  RedisTemplate<Object, Object> redisTemplate(RedisConnectionFactory connectionFactory) {

    RedisTemplate<Object, Object> template = new RedisTemplate<>() {

      @Override
      public ValueOperations<Object, Object> opsForValue() {
        return new WrapperValueOperations<>(super.opsForValue());
      }
    };

    template.setConnectionFactory(connectionFactory);

    return template;
  }
}
```

The abstract `DelegateValueOperations` class is not strictly necessary in this case, but 1) makes multiple implementations of the `ValueOperations` interface possible and cleanly delineated by concern (e.g. [ `LoggedValueOperations`, `TimedValueOperations`, `SecureValueOperations`, `TransactionalValueOperations` ]) and 2) configurable and easy to "[compose](https://en.wikipedia.org/wiki/Composite_pattern)" as a "single" `ValueOperations` implementation:

```java
@Override
public ValueOperations<K, V> opsForValue() {
  return new LoggedValueOperations(new TimedValueOperations(super.opsForValue());
}
```

Of course, there are arguably more effective ways to go about "wrapping" the `RedisTemplate` bean, such as by using [Spring AOP](https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#aop) to intercept operations (e.g. `opsForValue()`) on the declared and configured `RedisTemplate` bean inside a Spring context in order to wrap (decorate) (e.g.) the `ValueOperations` object returned by `opsForValue()`. You would simply need to supply a "decorated" version of `ValueOperations` interface (the _Advice_) and write an appropriate _Pointcut_ matching the join point (i.e. `opsForValue()` method) when configuring the _Aspect_ for the `RedisTemplate` bean.

In general, Spring does not provide interceptors for templates, such as `JdbcTemplate` provided by the core Spring Framework, or the many other template implementations provided in the Spring Data modules for their respective stores.

The configured "interceptor(s)" for `RestTemplate` are not exactly the same thing in this case, especially as I have described and illustrated above, since `RestTemplate's` interceptor(s) process low-level details of an HTTP request itself, such as the request body or headers, rather than individual operations on `RestTemplate`, specifically; that is, [here](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/client/support/InterceptingHttpAccessor.html#setInterceptors(java.util.List)) and then [here](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/client/ClientHttpRequestInterceptor.html#intercept(org.springframework.http.HttpRequest,byte%5B%5D,org.springframework.http.client.ClientHttpRequestExecution)).

With regards to `WebClient` filters, are you referring to [this](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/reactive/function/client/WebClient.Builder.html#filter(org.springframework.web.reactive.function.client.ExchangeFilterFunction))?

In any case, I will bring this back to the team to get additional thoughts and feedback. In the meantime, I hope the information I provided provides you with some guidance or help in your situation.

Thank you.

**Comment by radut** [comment]
Hi,
Thank you for quick and detailed response

I understand the reason of `final` keyword and encapsulation. 

> For instance, if the Spring [Data [Redis]] framework were to provide (additional) wrappers (or interceptors) around these operational interfaces, depending on the context, then you could possibly and inadvertently circumvent this decoration.

This is exactly what I am looking for.

In the first example that you provided, it is required that we create beans, and we define the way we create RedisTemplate ( probably we will need a factory which will create all kinds of redisTemplates, with overriden opsForValue, which will return our WrapperValueOperations)

The other option with AOP looks like we need to pointcut and return a new object every time opsForValue is used, instead of just adding to the stream/pipeline some operations. Objects are being created for each operation, which is not so friendly with GC and performs a bit slower.

The filter/interceptor examples were just to point out best option. I am familliar with them, I understand that they are lower level than opsForValue, but they do provide ways to wrap before-after request and doesn't require the developer to use a particular factory to create bean. 


This would be possible with RestTemplate:
```
@Autowired
List<RestTemplate> restTemplates;

@PostConstruct
public void init (){
 restTemplates.stream().forEach(restTemplate->{
       List<ClientHttpRequestInterceptor> interceptors  = restTemplate.getInterceptors();
        if (CollectionUtils.isEmpty(interceptors)) {
            interceptors = new ArrayList<>();
        }
        interceptors.add(new RestTemplateSomethingInterceptor()); //Logging, CircuitBreaker could be implemented here
        restTemplate.setInterceptors(interceptors);
} )
```

This could be added/removed at runtime, without redefining `restTemplate` beans, and it does not create new Objects/Interceptor on each request(operation).

**Comment by jxblum** [comment]
Understood. Thank you for the feedback and sharing the details.

1 additional tip here, of course, whether you are using the _Composite_ design pattern or Spring AOP, specifically, to avoid the excessive object creation everytime, say `redisTemplate.opsForValue()` is called is to do the following:

```java
@Configuration
class ApplicationRedisConfiguration {

  @Bean
  RedisTemplate<Object, Object> redisTemplate(RedisConnectionFactory connectionFactory) {

    return new RedisTemplate<>() {

      AtomicReference<ValueOperations><Object, Object> opsForValueRef = new AtomicReference<>(null);

      @Override
      ValueOperations<Object, Object> opsForValue() {
        return opsForValueRef.updateAndGet(it -> it != null ? it
          : new LoggingValueOperations(SecureValueOperations(super.opsForValue())));
      }
    };
  }
```

This technique can be applied to any of the operation interfaces delegated to by `RedisTemplate`.

Of course, you can also simply cache a reference to the `ValueOperations` instance in the manage application bean using the `RedisTemplate`, too:

```java
@Service
class MyRedisTemplateUsingService {

  private final ValueOperations valueOperations;

  MyRedisTemplateUsingService(@NonNull RedisTemplate redisTemplate) {
    Assert.notNull(redisTemplate, "RedisTemplate is required");
    this.valueOperations = redisTemplate;
  }

  // use valueOperations as needed in the service methods
}
```

Of course, without the use of the `AtomicReference` in the first example above, that will create additional objects for the `ValueOperations` instances required by each additional (service) bean that needs to use `ValueOperations` to carry out its functions.

The `AtomicReference` is quite useful in this situation, Thread-safe and only creates a single instance of `ValueOperations` object used by all application components/beans.

With minimal effort, this approach can even be used with Spring AOP. Remember, even though method invocations are unique per call (e.g. `redisTemplate.opsForValue()`), the AOP proxy for the `RedisTemplate` is only created once and the `RedisTemplate` bean is still a _Singleton_ instance, which you can use to your advantage, here.

Again, I prefer the _Composite_ approach even over Spring AOP in this case since it can even be used outside of a Spring context.

Cheers!

**Comment by jxblum** [comment]
Closing due to no further activity on this Issue ticket.
