### ISSUE TITLE
Remove a unnecessary Thread.sleep() from ClusterCommandExecutor.collectResults()

### ISSUE THREAD

**Issue by dongmyo** [spring-projects/spring-data-redis#2518]
https://github.com/spring-projects/spring-data-redis/blob/main/src/main/java/org/springframework/data/redis/connection/ClusterCommandExecutor.java#L224

when for loop ends with all futures done or cancelled in `ClusterCommandExecutor.collectResults()`.

https://github.com/spring-projects/spring-data-redis/blob/main/src/main/java/org/springframework/data/redis/connection/ClusterCommandExecutor.java#L258

after that, there is no need for thread to be slept, but `Thread.sleep()` is called unnecessarily.

it could be better to check if the `done` is false.

```
try {
    if (!done) {
        Thread.sleep(10);
    }
} catch (InterruptedException e) {
    // ...   
}
```

**Comment by jxblum** [comment]
Hi @dongmyo -

I appreciate your raising this issue; nice catch! I also think you are generally correct, here. However, I have been giving this some serious thought, off-and-on, for the past few days while working through other SD Redis Issues in our backlog.

In summary, I am thinking this `Thread.sleep()` call should be removed altogether as I am not entirely convinced that 1) it is strictly necessary, and 2) cannot be achieved in another, productive way (such as with `Future.get(timeout, :TimeUnit)`, [here](https://github.com/spring-projects/spring-data-redis/blob/3.0.3/src/main/java/org/springframework/data/redis/connection/ClusterCommandExecutor.java#L237-L239)).

I think the code will need to be restructured, which should help simplify the code a bit since it is rather complex to reason about, IMO. It also does not appropriately handle the `CancelationException` that can be thrown from [`Future.get()`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Future.html#get--), which is [not documented](https://github.com/spring-projects/spring-data-redis/blob/3.0.3/src/main/java/org/springframework/data/redis/connection/ClusterCommandExecutor.java#L181-L187) (nor [here](https://github.com/spring-projects/spring-data-redis/blob/3.0.3/src/main/java/org/springframework/data/redis/connection/ClusterCommandExecutor.java#L272-L278)) either, where the `collectResults(..)` method is invoked (part of the public API).

In general, calling `Thread.sleep(..)` is dangerous for at least 2 reasons:

1) Threads in Java are native to the platform on with the JRE is built/ran (unlike the Green Threads, or Project Loom, to an extent, which is on the horizon). Therefore, Java Threads are subject to the vagaries of scheduling and behavior consistent with the underlying OS and Thread model in use.

2) Secondly, arbitrary `Thread.sleep(..)` timeouts (e.g. 10 milliseconds +/-) might be perfectly acceptable in some applications while detrimental in others. What is too much or too little? And with Redis being all about efficient/fast access to data, this sort of induced latency is questionable at best.

My plan of attack is to write some test for this area of code so that I can begin make (structural) changes that ultimately get rid of the `Thread.sleep(..)` altogether.

I will post back when I have more information to share.

**Comment by dongmyo** [comment]
@jxblum thank you for your response.
either way, it will be fine as long as unnecessary `Thread.sleep()` is going to be removed.

**Comment by jxblum** [comment]
I am finally, now circling back to this.

Knowing significantly more about Spring Data Redis and just Redis now, my thinking as that this "arbitrary" `Thread.sleep()` call ([here](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/connection/ClusterCommandExecutor.java#L256-L262)) can be simply removed altogether. It really serves no purpose.

The [Future.get()](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/Future.html#get()) calls ([here](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/connection/ClusterCommandExecutor.java#L236) and [here](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/connection/ClusterCommandExecutor.java#L238)) "_waits until the computation completes_" anyway.

So, I think it is also unnecessary to use `Future.get(timeout, :TimeUnit)` in this case given blocking/waiting nature of `Future.get()` in the first place, though, it may not be the most effective use of "collecting results" across a collection of nodes in the Redis cluster.

Additionally, after looking through this code, I also think there is a bug!

If execution fails for any node when evaluating the result, then there is no point to re-evaluate the node on a subsequent iteration (in the `while` loop). That is, I think the `futureId` should be added to the `saveGuard` (as [so](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/connection/ClusterCommandExecutor.java#L240)) inside the `ExecutionException` handler [block](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/connection/ClusterCommandExecutor.java#L242-L245).

Finally, it is not necessary to "handle" the `CancellationException` as I previously stated.

**Comment by rishiraj88** [comment]
Very impressive issue. Thanks.

**Comment by jxblum** [comment]
Opened PR #2719, which is pending review and merge.

**Comment by jxblum** [comment]
Technically, after further review and careful consideration, I should clarify that the `Thread.sleep(..)` is possibly useful when [none of the Future results are complete yet](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/connection/ClusterCommandExecutor.java#L225-L226). 

Depending on the `Future` implementation, without a **pause**, the `while` loop ([here](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/connection/ClusterCommandExecutor.java#L220-L263)) inside `ClusterCommandExecutor.collectResults(..)` could run hot and wind up being a "busy" loop.

The new implementation is [here](https://github.com/spring-projects/spring-data-redis/blob/issue/2518/src/main/java/org/springframework/data/redis/connection/ClusterCommandExecutor.java#L255-L295), along with [this](https://github.com/spring-projects/spring-data-redis/blob/issue/2518/src/main/java/org/springframework/data/redis/connection/ClusterCommandExecutor.java#L309-L321).

I also reduced the `Thread.sleep(1L)` to 1 millisecond.

> NOTE: I could have chosen to use a `TimeUnit.timedWait(..)` ([Javadoc](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/concurrent/TimeUnit.html#timedWait(java.lang.Object,long))), thereby reducing the latency even further to MICROSECONDS (e.g. `TimeUnit.MICROSECONDS.timedWait(obj, 10)`) or even NANOSECONDS, but that requires a `synchronized` block on an `Object` monitor (or an object's intrinsic lock). This would limit scalability in the context of Virtual Threads.

**Comment by jxblum** [comment]
On second thought, recalling some thoughts I had earlier, I do think there is a way to remove the `Thread.sleep(..)` call altogether.

I switched the PR to DRAFT mode for the time being.

**Comment by jxblum** [comment]
Alright, PR #2719 re-opened (no longer in draft mode).

I also modified the PR to now remove `Thread.sleep(..)` completely! You can read the [commit message](https://github.com/spring-projects/spring-data-redis/pull/2719/commits/0a5c34279d70328a5e544ef6716b2ed57e5e37a4) to the reasoning behind the current thinking and set of changes.
