### ISSUE TITLE
Does `ReactiveRedisTemplate` support transactions

### ISSUE THREAD

**Issue by labulalala** [spring-projects/spring-data-redis#2520]
I'm using  `ReactiveRedisTemplate` for connecting and querying Redis in a non blocking way. When I want to use transactions, I cannot find a way to do that. I browsed the [doc](https://docs.spring.io/spring-data/data-redis/docs/current/reference/html/#tx) and I found it only supports `RedisTemplate`. 
Does `ReactiveRedisTemplate` support transactions and how to use. Thanks

**Comment by mp911de** [comment]
No, because transactions aren't a good fit for reactive usage. The reactive command infrastructure sends a command to the Redis server when a reactive subscriber requests data. Because transactions do not complete commands immediately, but rather when a terminal `EXEC` command is sent, it is very easy to end up with a deadlock waiting for responses with a little prefetch (concatMap, flatMap).

You would need to call `.subscribe()` on each command within the transaction, which is an antipattern in reactive programming. Therefore, we decided to not provide reactive transaction support.
