### ISSUE TITLE
RedisTemplate should have opsForValue(RedisSerializer<?> redisSerializer)

### ISSUE THREAD

**Issue by livk-cloud** [spring-projects/spring-data-redis#2562]
`ReactiveRedisTemplate` has

```
org.springframework.data.redis.core.ReactiveRedisTemplate.opsForValue(org.springframework.data.redis.serializer.RedisSerializationContext<K1,V1>)
```

It should also have `opsForList`, etc.

**Comment by jxblum** [comment]
@livk-cloud - Could you please clarify your ask here?

Starting from the beginning, in your title, you state, "_RedisTemplate (as in [this](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/core/RedisTemplate.html)) should have `opsForValue(:RedisSerializer)`_"

However, the overloaded variant of `opsForList(:RedisSerializer)` (as suggested) would be\ inconsistent with any of the `RedisTemplate`, or rather `RedisOperations` ([Javadoc](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/core/RedisOperations.html)), `opsForXyz()` API (methods). For example, the comparable `RedisOperations.opsForSet()` API method ([Javadoc](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/core/RedisOperations.html#opsForSet())) takes no serialization context, or `RedisSerializer` in particular.

In addition, all the operational  extensions (`opsForXyz()` methods) used and delegated to by the `RedisTemplate` are constructed with the encapsulating `RedisTemplate` reference itself ([source](https://github.com/spring-projects/spring-data-redis/blob/3.0.5/src/main/java/org/springframework/data/redis/core/RedisTemplate.java#L112-L120)).

And, because the `RedisTemplate` can be configured with [HashKey](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/core/RedisTemplate.html#setHashKeySerializer(org.springframework.data.redis.serializer.RedisSerializer)), [HashValue](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/core/RedisTemplate.html#setHashValueSerializer(org.springframework.data.redis.serializer.RedisSerializer)), [Key](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/core/RedisTemplate.html#setKeySerializer(org.springframework.data.redis.serializer.RedisSerializer)) and [Value](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/core/RedisTemplate.html#setValueSerializer(org.springframework.data.redis.serializer.RedisSerializer)) `RedisSerializers` independently, in addition to a default `RedisSerializer` overall ([here](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/core/RedisTemplate.html#setDefaultSerializer(org.springframework.data.redis.serializer.RedisSerializer))), and [enable it](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/core/RedisTemplate.html#setEnableDefaultSerializer(boolean)) on the template, then it is a trivial matter to create additional templates to customize the serialization of values used and processed by your application independently, if needed. This is clearly very application specific, depending on your use case and requirements and not necessarily a convenience that the framework should provide since it would be all too easy for users to get this wrong.

**Comment by jxblum** [comment]
@livk-cloud - Regarding your description (which is completely and seemingly unrelated to the "title") in this issue ticket, where the `ReactiveRedisTemplate` has the opsForValue(:RedisSerializationContext)` method ([Javadoc](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/core/ReactiveRedisTemplate.html#opsForValue(org.springframework.data.redis.serializer.RedisSerializationContext))) and should also have a `opsForList(:RedisSerializationContext)` method... well, this class does:

* `opsForList()` ([Javadoc](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/core/ReactiveRedisTemplate.html#opsForList()))
*  `opsForList(:RedisSerializationContext)` ([Javadoc](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/core/ReactiveRedisTemplate.html#opsForList(org.springframework.data.redis.serializer.RedisSerializationContext)))

**Comment by jxblum** [comment]
Was going to check the API in Spring Data Redis `2.7.x` from [here](https://spring.io/projects/spring-data-redis#support), but apparently the Javadoc for `2.7.x` is inaccessible at the moment. #sigh

**Comment by jxblum** [comment]
After reviewing the locally built Javadoc, the API is the same for both `RedisTemplate`, `opsForXyz()` methods (such as `opsForValue()`, etc) as well as the `ReactiveRedisTemplate` class, which provides both:

* `opsForList()`
*  `opsForList(:RedisSerializationContext)`

If your using an earlier version of Spring Data Redis prior to `2.7.x` (for example: `2.6.x` or earlier), then you should know that SD Redis OSS support for `2.6.x` and earlier has ended. See [support timelines](https://spring.io/projects/spring-data-redis#support) for further details.

This means that, since OSS support has ended, there will be no further patches or service releases to SD Redis `2.6` (`2.6.10` was the last service release) or earlier and you will need to upgrade to SD Reids `2.7`, minimally.

However, keep in mind, even SD Redis `2.7` is tentatively scheduled for OSS support EOL as of May 2023. Again, see [support timelines](https://spring.io/projects/spring-data-redis#support). Technically, even SD Redis `2.7.x` has already entered OSS support EOL. Still we have 1 last scheduled release on Friday, May 12, 2023; see [here](https://calendar.spring.io/).

If you require "extended" support for SD Redis `2.5` or `2.6`, when you will need to purchase a [VMware Spring Runtime](https://tanzu.vmware.com/spring-runtime) license to get the "commercial" support dates.

**Comment by livk-cloud** [comment]
@jxblum first of all thank for your answer。 
> Sorry, English is not my mother tongue, the expression may be a little lacking
> My thinking is that RedisTemplate needs an overloaded method of ` opsForValue(RedisSerializer<?> redisSerializer)`, like ReactiveRedisTemplate, which has `opsForValue()` and `opsForValue(RedisSerializationContext<K1, V1> serializationContext)`. In this way, RedisTemplate can be a complete singleton, instead of building multiple RedisTemplates to adjust different serialization methods


```java
public class RedisTemplate<K, V> extends RedisAccessor implements RedisOperations<K, V>, BeanClassLoaderAware {

	@Override
	public ValueOperations<K, V> opsForValue() {
		return valueOps;
	}

       //I feel the need for a method like this
       public ValueOperations<K, V> opsForValue(RedisSerializer<V> valueSerializer) {
              //return ValueOperations instance
       }
}
```

> but from your description, this is a design issue. Maybe my idea is good, but relative to the current situation, it is not practical. Anyway, thanks for your answer, this `issue` should be closed

**Comment by jxblum** [comment]
Thank you @livk-cloud.
