### ISSUE TITLE
lettuce can't read data

### ISSUE THREAD

**Issue by zhou-shiliu** [spring-projects/spring-data-redis#2569]
In this project, spring-boot-starter-data-redis:2.6.8 client version is used, and redis cluster uses redis5.0.14 version. By default, data can be written into the lettuce mode, but cannot be read. Jedis should be used to read data.

**Comment by jxblum** [comment]
First, both Spring Boot `2.6.x` and Spring Data Redis `2.6.x` are no longer in OSS support.  See the support timelines for Spring Boot ([here](https://spring.io/projects/spring-boot#support)) and Spring Data Redis ([here](https://spring.io/projects/spring-data-redis#support)) for more details.

> NOTE: Also, even Spring Boot `2.7`, and correspondingly, Spring Data Redis `2.7` OSS support ends this month, **May 2023**.

> NOTE: `spring-boot-starter-data-redis:2.6.8` pulls in Spring Data Redis `2.6`.

If you require support, then you would need to purchase a VMware Spring Runtime (VSR) license (see [here](https://tanzu.vmware.com/spring-runtime)). The same action would be required for Spring Boot/Spring Data Redis `2.7` after 2023-May-01`.  Otherwise, and most likely, you would need to upgrade to Spring Boot / Spring Data Redis `3.x` (e.g. SD Redis `3.0.5`).

> WARNING: Spring Boot `3` and Spring Data (Redis) `3` also minimally requires **Java 17** and **Jakarta EE 9/10** as per the Spring Framework `6.0` requirement.

When you say:

> _"By default, data can be written into the lettuce mode, but cannot be read. Jedis should be used to read data."_

Data can be written using "Lettuce mode", but cannot be read, what do you even mean?  [Lettuce](https://lettuce.io/) is a Redis (client) driver for interacting with either a standalone Redis server, or alternatively, a Redis cluster.  Lettuce is a Redis (client) driver like Jedis. Both drivers provide many of the same capabilities and functionality.

However, it is ill-advisable to use Lettuce to write and Jedis to read in the same application.  There are many factors why this is never a good idea, including, but not limited to: consistency, transactions, pub/sub, etc.

You could certainly have 2 separate (Spring [Boot]) applications, where 1 application simply writes to the Redis server(s) and the other application only reads from the Redis server(s). But you never would use connections from 2 different Redis client drivers in the same appliaction.

It is also possible that I am not understanding your use case or requirements in this situation.

If you can supply evidence of an actual problem in Spring Data Redis and its use/interactions with the Lettuce Redis client driver, such as a minimal example or test, along with configuration, Stack Traces, Thread dumps and Logs to reproduce the issue, then we'd be happy investigate further.

**Comment by jxblum** [comment]
Although, seemingly unlikely, the problem you are having could be a problem with the Lettuce, Redis (client) driver itself, in which case, you should follow up with the [Lettuce project](https://lettuce.io/)/team specifically since we do not own this project.  See [here](https://lettuce.io/core/release/reference/index.html#overview.support).
