### ISSUE TITLE
LettucePoolingConnectionProvider contains unreleased connections if RedisConnectionFactory is spied by Mockito

### ISSUE THREAD

**Issue by quaff** [spring-projects/spring-data-redis#2570]
see https://github.com/spring-projects/spring-boot/issues/35188

**Comment by jxblum** [comment]
Spring Data Redis's (SDR) [`RedisConnectionFactory`](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/connection/RedisConnectionFactory.html) is nothing more than an (Adapter) interface and facade for _Jedis_ and _Lettuce_ based driver connections and configuration, using the appropriate factories.

Given the interaction in your Spring application tests involves the SD Redis `LettucePoolingConnectionProvider`,  no doubt you are using the [Lettuce](https://lettuce.io/) Redis (client) driver, and it would imply you have declared and configured the `LettuceConnectionFactory` (as described [here](https://docs.spring.io/spring-data/redis/docs/current/reference/html/#redis:connectors:lettuce), possibly??).

It is rather odd (and arguably unnecessary) to spy on or even mock the `RedisConnectionFactory` as this would unduly, tightly couple your Spring (Data Redis) application to the functionality and behavior of the Lettuce (or even Jedis) driver and interactions between the driver and the Lettuce-based `RedisConnectionFactory` "implementation", which is subject to change!

By spying on, or mocking the `LettuceConnectionFactory`, you may also have inadvertently affected the lifecycle of the Spring managed bean. Is your "spy" of the `RedisConnectionFactory` (`LettuceConnectionFactory` instance) even a managed bean in the Spring container?

The reason this is important is because in SD Redis, both the `LettuceConnectionFactory` and the `JedisConnectionFactory` (for that matter) implement Spring container lifecycle interfaces (i.e. [`InitializingBean`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/factory/InitializingBean.html) and [`DisposableBean`](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/beans/factory/DisposableBean.html)). For example, see `LettuceConnectionFactory` [Javadoc](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/connection/lettuce/LettuceConnectionFactory.html).

As you might imagine,  the `InitializingBean` callback could be used to initialize a connection pool with (Lettuce) Redis client connections. Subsequently, on Spring container/application shutdown, the `DisposableBean` callback can be used to close connections and cleanup resources.

This is precisely what the `LettuceConnectionFactory`, `destroy()` (callback) method (from the `DisposableBean` interface) does, in fact; see [here](https://github.com/spring-projects/spring-data-redis/blob/3.0.5/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnectionFactory.java#L345-L374).

Therefore, I suspect your mocking/spying issues are self-inflicted. 

Without further evidence to support that Spring Data Redis is possibly at fault in this case, this is not something we will address. Minimally, you should supply an example or test reproducing the problem, complete with configuration, along with any _Stack Traces_, _Thread dumps_ or Logs that will aid in the reproduction and debugging of this issue.

**Comment by quaff** [comment]
I've supplied a [minimal example](https://github.com/spring-projects/spring-boot/files/11349980/warning.zip) in (https://github.com/spring-projects/spring-boot/issues/35188), `@SpyBean` doesn't affect lifecycle, `afterPropertiesSet` and `destroy` is called as expected.

**Comment by jxblum** [comment]
Upon closer inspection, I think your concerns are a bit misguided since you superficially stopped at the `WARN` logger message that is output at the beginning of the `LettucePoolingConnectionProvider.destroy()` method (see [here](https://github.com/spring-projects/spring-data-redis/blob/3.0.5/src/main/java/org/springframework/data/redis/connection/lettuce/LettucePoolingConnectionProvider.java#L204-L206)).

> NOTE: The `LettucePoolingConnectionProvider.destroy()` method is called from the `LettuceConnectionFactory.destroy()` ([here](https://github.com/spring-projects/spring-data-redis/blob/3.0.5/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnectionFactory.java#L358-L359)) method to cleanup all resources, including pooled connections to Redis server(s).

In fact, the `LettucePoolingConnectionProvider.destroy()` method will go on to release connections ([here](https://github.com/spring-projects/spring-data-redis/blob/3.0.5/src/main/java/org/springframework/data/redis/connection/lettuce/LettucePoolingConnectionProvider.java#L214-L224)) and then eventually close all connections ([here](https://github.com/spring-projects/spring-data-redis/blob/3.0.5/src/main/java/org/springframework/data/redis/connection/lettuce/LettucePoolingConnectionProvider.java#L226)) as appropriate.

Spring Data Redis will even make an attempt to wait for the process of closing connections to complete (see [here](https://github.com/spring-projects/spring-data-redis/blob/3.0.5/src/main/java/org/springframework/data/redis/connection/lettuce/LettucePoolingConnectionProvider.java#L208-L212), then [here](https://github.com/spring-projects/spring-data-redis/blob/3.0.5/src/main/java/org/springframework/data/redis/connection/lettuce/LettucePoolingConnectionProvider.java#L228-L242)).

Finally, all connection object references stored in the pool are cleared to avoid dangling references during JVM garbage collection (see [here](https://github.com/spring-projects/spring-data-redis/blob/3.0.5/src/main/java/org/springframework/data/redis/connection/lettuce/LettucePoolingConnectionProvider.java#L244)), which may be moot point if your entire application/system is being shutdown. Otherwise, if only the Redis components of the Spring application are being stopped, then it would appear Spring Data Redis made best effort to release resources appropriately.

Technically, the WARN logger message is simply used to inform the user that connections are still present when the application is shutdown.

AFAICT, Spring Data Redis is doing the right thing in this case.

I also found a related Issue ticket #1404 that was addressed back in Spring Data (Redis) `2.1` (Lovelace) even.

Again, how is Spring Data Redis causing any issue here?

**Comment by quaff** [comment]
It's Interesting that https://github.com/spring-projects/spring-data-redis/issues/1404 is opened by me too. This issue is not trouble me that much, my intent is to make SDR working better with @SpyBean, If you think it's trivial feel free to ignore.

**Comment by quaff** [comment]
Finally I resolved the puzzle.
https://github.com/spring-projects/spring-data-redis/blob/2246a98a9388a14be6964402a75e258f257788e7/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnectionFactory.java#L120-L121
Those two `SharedConnection` is held by spied instead of original `RedisConnectionFactory`, It's out of spring container's control, can not be reset by destroying original `RedisConnectionFactory`.

```java
@SpringBootTest
@TestPropertySource(properties = "logging.level.root=INFO")
public class ApplicationTests {

	@Autowired
	private RedisConnectionFactory redisConnectionFactory;

	@Test
	void test() throws Exception {
		RedisConnectionFactory spied = Mockito.spy(redisConnectionFactory);
		try (RedisConnection conn = spied.getConnection()) {

		}
		if (spied instanceof LettuceConnectionFactory lcf) {
			lcf.resetConnection(); // reset connection and reactiveConnection
		}
	}

}

```

I'm wondering if spring-data-redis could improve to eliminate
```java
if (spied instanceof LettuceConnectionFactory lcf) {
	lcf.resetConnection(); // reset connection and reactiveConnection
}
```

**Comment by jxblum** [comment]
I still question the need to "spy on" (or even "mock", for that matter) the `RedisConnectionFactory`.

What purpose does it serve during testing, even if integration testing?

**Comment by quaff** [comment]
@jxblum I want verify commands are sent to redis instance, and I don't want to mock interfaces it need lots of code.

```java
@SpringBootTest
@TestPropertySource(properties = "logging.level.root=INFO")
public class ApplicationTests {

	@SpyBean
	private RedisConnectionFactory redisConnectionFactory;

	@Autowired
	private StringRedisTemplate redisTemplate;

	@Test
	void test() {
		ResultCaptor<RedisConnection> resultCaptor = new ResultCaptor<>(Mockito::spy);
		given(this.redisConnectionFactory.getConnection()).willAnswer(resultCaptor);
		redisTemplate.opsForValue().set("test", "value"); // triggered by some real services
		then(resultCaptor.getResult()).should().set("test".getBytes(), "value".getBytes());
	}

	static class ResultCaptor<T> implements Answer<T> {

		private T result;

		private final UnaryOperator<T> operator;

		public ResultCaptor() {
			this.operator = UnaryOperator.identity();
		}

		public ResultCaptor(UnaryOperator<T> operator) {
			this.operator = operator;
		}

		public T getResult() {
			return this.result;
		}

		@SuppressWarnings("unchecked")
		@Override
		public T answer(InvocationOnMock invocationOnMock) throws Throwable {
			this.result = this.operator.apply((T) invocationOnMock.callRealMethod());
			return this.result;
		}

	}
}

```
