### ISSUE TITLE
Redis health check executes a command that requires a potentially sensitive permission

### ISSUE THREAD

**Issue by arana3** [spring-projects/spring-data-redis#2582]
Both the out of box RedisHealthCheck and RedisReactiveHealthCheck execute **CLUSTER INFO** command. In order to execute such command, the associated user that the underlying driver will use must have minimally the _@slow_ ACL.

@slow ACL also provides permissions to modification commands under the **CLUSTER** group (ex. node reset, slot allocation).

There are definitely organizations whose security posture may not  allow an backend app user to have the noted ACL.

The only immediate alternative I can quickly think of is to let the out of box health checks execute something like xinfo or less impactful commands.

Thoughts? Should this be called out in class level Javadoc and documentation? 

Reference Links:
- https://redis.io/commands/cluster-info/

**Comment by jxblum** [comment]
Upon closer inspection of Spring Boot's `RedisHealthIndicator` ([Javadoc](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/actuate/data/redis/RedisHealthIndicator.html), [source](https://github.com/spring-projects/spring-boot/blob/v3.0.6/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/data/redis/RedisHealthIndicator.java)) and `RedisReactiveHealthIndicator` ([Javadoc](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/actuate/data/redis/RedisReactiveHealthIndicator.html), [source](https://github.com/spring-projects/spring-boot/blob/v3.0.6/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/data/redis/RedisReactiveHealthIndicator.java)) classes, 
I suspect this is what you are referring into instead (actually).

**Comment by jxblum** [comment]
Mark (@mp911de), can you please comment on this ticket as well?

Thank you.

**Comment by jxblum** [comment]
1 more thing...

I was reviewing the Redis `INFO` command (which is used by Spring Boot to collect health information on "servers" when the Redis connection is not "clustered").

The Redis `INFO` command ([doc](https://redis.io/commands/info/)) contains a section for "cluster". However, the information is very limited:

```txt
# Cluster
cluster_enabled:0
```

The "cluster" `INFO` command effectively only reveals whether the clustered feature of Redis is enabled, which is why Spring Boot simply returns the Redis (server) version ([here](https://github.com/spring-projects/spring-boot/blob/v3.0.6/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/data/redis/RedisHealth.java#L37)) in the health information.

However, with the Reids `CLUSTER_INFO` command, Spring Boot's `HealthIndicator` can collect a bit more details on the cluster as I alluded to in my first comment; see [here](https://github.com/spring-projects/spring-boot/blob/v3.0.6/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/data/redis/RedisHealth.java#L42-L48).

**Comment by mp911de** [comment]
Spring Boot provides all health-check code. I'm not a big fan of showing all cluster details in the health check either, a cluster `PING` would be more suited. However, with a cluster the question is whether you want to ping a single node, all nodes and what the effect of that would be. Probably, pinging a single node would be sufficient.
