### ISSUE TITLE
Timestamp handling regression 2.7.12 -> 3.0.0

### ISSUE THREAD

**Issue by lpandzic** [spring-projects/spring-data-redis#2593]
Following code works fine on 2.7.12 but fails on 3.0.0:
```
@Test
void shouldNotFail() {
    // given
    var given = Map.<String, Object>of("lastAssigment", "2023-06-05T11:08:33.107451Z");

    // when
    var actual = BDDAssertions.catchRuntimeException(() -> mapper.fromHash(given));

    // then
    then(actual).isNull();
}
```

```
org.opentest4j.AssertionFailedError: 
expected: 
  null
 but was: 
  org.springframework.data.mapping.MappingException: Could not resolve subtype of [simple type, class java.lang.Object]: missing type id property '@class'
   at [Source: (byte[])"{"lastAssigment":"2023-06-05T11:08:33.107451Z"}"; line: 1, column: 47]
   ```

**Comment by lpandzic** [comment]
Classpath contains following jackson modules:
jackson-datatype-jdk8
jackson-module-parameter-names
jackson-module-kotlin

**Comment by lpandzic** [comment]
Quick note: it happens on 3.0.0-M1

**Comment by jxblum** [comment]
Upon closer analysis of this issue, this problem does not only affect timestamps (such as date/time fields), but also non-evaluated scalar values, such as `BigDecimals` and `BigIntegers`, too (though values for fields/properties of these types can and should be treated as scalar values).

For instance, in test class `Jackson2HashMapperUnitTests` ([source](https://github.com/spring-projects/spring-data-redis/blob/3.1.0/src/test/java/org/springframework/data/redis/mapping/Jackson2HashMapperUnitTests.java)), there are 3 tests failing as of SD Redis `3.0.0-M5` for the reason shown above:

* `dateValueShouldBeTreatedCorrectly`
* `bigDecimalShouldBeTreatedCorrectly`
* `bigIntegerShouldBeTreatedCorrectly`

Technically caused by (for example):

```
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Unexpected token (VALUE_NUMBER_INT), expected START_ARRAY: need Array value to contain `As.WRAPPER_ARRAY` type information for class java.math.BigInteger
 at [Source: (byte[])"{"@class":"org.springframework.data.redis.mapping.Jackson2HashMapperUnitTests$WithBigWhatever","bigI":10}"; line: 1, column: 103] (through reference chain: org.springframework.data.redis.mapping.Jackson2HashMapperUnitTests$WithBigWhatever["bigI"])
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.wrongTokenException(DeserializationContext.java:1950)
...
..
.
```

Therefore, this specific problem reproduces with the (flattened) `Jackson2HashMapperUnitTests.dateValueShouldBeTreatedCorrectly` test case [method](https://github.com/spring-projects/spring-data-redis/blob/3.1.0/src/test/java/org/springframework/data/redis/mapping/Jackson2HashMapperUnitTests.java#L175-L186), already.

Unfortunately, this test class is not being run as part of the SD Redis test suite using `$ make test`, for some non-apparent reason to me, yet.

Additionally, this problem only occurs for the "flattened" configuration.

**Comment by jxblum** [comment]
Upon even closer inspection, the only reason why this properly worked in the past (i.e. with SD Redis `2.7.x` or earlier) is because either the "hash" (`Map` object passed to `fromHash(..)`) had to contain type metadata (such as with the `@class` JSON metadata property, which could be provided by a `JsonTypeInfo.Id.CLASS` declaration on the "_valueType_" to be mapped) or by specifically calling the `fromHash(..)` method with the target `Class` type, as was [previously available](https://github.com/spring-projects/spring-data-redis/blob/2.7.x/src/main/java/org/springframework/data/redis/hash/Jackson2HashMapper.java#L286) in SD Redis `2.7.x`, (along with [this](https://github.com/spring-projects/spring-data-redis/blob/2.7.x/src/main/java/org/springframework/data/redis/hash/Jackson2HashMapper.java#L294)) but was subsequently removed in SD Redis `3.0` and later, [here](https://github.com/spring-projects/spring-data-redis/blob/3.0.0-M1/src/main/java/org/springframework/data/redis/hash/Jackson2HashMapper.java#L226), and then simply [given a type of `Object.class`](https://github.com/spring-projects/spring-data-redis/blob/3.0.0-M1/src/main/java/org/springframework/data/redis/hash/Jackson2HashMapper.java#L232), thereby resulting in a loss of information necessary to properly resolve the mapping.

**Comment by jxblum** [comment]
There is still some issue with newer versions Jackson combined with SD Redis `3.0.x+` that is not clear to me. More investigation is needed...

**Comment by lpandzic** [comment]
This was tested against jackson bom 2.14.2 first and 2.13.5 second as I first suspected this could be an issue with jackson. On other projects during Spring Boot 3 migration I've already faced issues with jackson 2.15.0 and 2.15.1 and records. Changing jackson doesn't affect this case in any way from my perspective (and the provided test).

**Comment by lpandzic** [comment]
Some change between 2.7.12 and 3.0.0-M1 is causing this.
During my investigation yesterday my next suspect on the list was this commit - https://github.com/spring-projects/spring-data-redis/commit/93c25b0608173fafaddb485c539b84ab4db5801d but I haven't checked it as 2.7.12 is good enough for me and I can move on.
