### ISSUE TITLE
ClusterConnectionProvider might cause TCP connection leak

### ISSUE THREAD

**Issue by 970655147** [spring-projects/spring-data-redis#2619]
this is a project using spring-data-redis, spring-boot-actuator 
there are 2 case, might reoccur that 
1. config address that isn't redis server, follow try a  mysql services, 
then visit "http://localhost:8080/actuator/health", there leak 6 tcp connection each visit 
`
spring.redis.cluster.nodes: 192.168.220.133:3306,192.168.220.133:3307,192.168.220.133:3308,192.168.220.133:3309,192.168.220.133:3310,192.168.220.133:3311
`

2. config redis server with password, but didn't config "spring.redis.password"
then visit "http://localhost:8080/actuator/health", there leak 6 tcp connection each visit 
`
spring.redis.cluster.nodes: 192.168.220.133:7001,192.168.220.133:7002,192.168.220.133:7003,192.168.220.133:7004,192.168.220.133:7005,192.168.220.133:7006
`

use "ll /proc/$pid/fd | grep socket" to watch connections

**Comment by jxblum** [comment]
Actuator is part of Spring Boot, not Spring Data Redis.

**Comment by 970655147** [comment]
> 

but core code is in spring-data-redis, main context in LettuceConnectionFactory$SharedConnection.getConnection 
if ClusterConnectionProvider.getConnection throw Exception, there maybe tcp connection leak 
spring-boot-acurator is just a trigger in this context

**Comment by 970655147** [comment]
> 

but core code is in spring-data-redis, main context in LettuceConnectionFactory$SharedConnection.getConnection 
if ClusterConnectionProvider.getConnection throw Exception, there maybe tcp connection leak 
spring-boot-acurator is just a trigger in this context

**Comment by 970655147** [comment]
> Actuator is part of Spring Boot, not Spring Data Redis.

sorry, my presentation is not exactly 
but core code is in spring-data-redis, main context in LettuceConnectionFactory$SharedConnection.getConnection 
if ClusterConnectionProvider.getConnection throw Exception, there maybe tcp connection leak 
spring-boot-acurator is just a trigger in this context

**Comment by jxblum** [comment]
Let me review and evaluate this further.

**Comment by jxblum** [comment]
Closed by mistake.

**Comment by jxblum** [comment]
After further analysis, I am not convinced that this is necessarily a problem with Spring Data Redis.

To state this case slightly differently, what would you expect to happen in this case (regarding this statement):

> "_if ClusterConnectionProvider.getConnection throw Exception, there maybe tcp connection leak
spring-boot-acurator is just a trigger in this context_"

And specifically, when an Exception is thrown from `ClusterConnectionProvider.getConnection()`? Close the connection?  But, by who/what? How? And, when?

I agree that the `RedisConnection` should not leak TCP socket resources.

You could argue that Spring Data Redis should be responsible for closing and cleaning up any resources acquired by the `RedisConnection`, but this depends on the "type" of Exception in the first place, in addition to the context/use case (e.g. Spring Boot Actuator), as well as whether any useful information could be derived from the Exception along with the state of the `RedisConnection`, both before and after the Exception occurs, that would possibly dictate how it is "handled".

Typically, a connection (e.g. `RedisConnection`) to some resource (e.g. Redis server) is established for some purpose, it is handed off to the user (consumer) and the user is left to be responsible for "releasing" that connection, where the "how" and "when" is application and use case dependent. This is not unlike other data access frameworks, such as JDBC. With JDBC, it would be "driver" (vendor) dependent.

So, having said this, you could argue that 1) Since a `RedisConnection` is `AutoCloseable` ([Javadoc](https://docs.spring.io/spring-data/redis/docs/2.7.12/api/org/springframework/data/redis/connection/RedisConnection.html)) and 2) the Spring Boot Actuator `HealthIndicator` for Redis [did not safely acquire](https://github.com/spring-projects/spring-boot/blob/v2.7.13/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/redis/RedisHealthIndicator.java#L49-L55) a `RedisConnection`, that it is then Spring Boot's responsibility. The health logic inside Spring Boot Actuator's `RedisHealthIndicator` should technically be:

```java
try (RedisConnection connection = RedisConnectionUtils.getConnection(this.redisConnectionFactory))  {
	doHealthCheck(builder, connection);
}
finally {
	RedisConnectionUtils.releaseConnection(connection, this.redisConnectionFactory);
}
```

By establishing a `RedisConnection` outside the `try-finally` block, when an Exception occurs, the logic inside the `finally` block (i.e. "release" the `RedisConnection`) will NOT get executed.

However, unlike JDBC, and even unlike Jedis (though maybe more similar to Reactive) is that opening `RedisConnections` using the Lettuce driver is "async". This certainly complicates the "when" the connection established.

Although, in this particular case/context (`RedisHealthIndicator` for Spring Boot Actuator), we see that the SD Redis `RedisConnectUtils.getConnection(:RedisConnectionFactory)` method was invoked ([here](https://github.com/spring-projects/spring-boot/blob/v2.7.13/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/redis/RedisHealthIndicator.java#L49)). If you trace this all the way through, we eventually arrive [here](https://github.com/spring-projects/spring-data-redis/blob/2.7.13/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnectionProvider.java#L53).

You can see that Lettuce `RedisConnections` are established (opened) "async", and that SD Redis "`joins`" on the `CompletableFuture` to turn an otherwise asynchronous operation into a synchronous, blocking call.

Given that the Lettuce driver is [returning](https://github.com/spring-projects/spring-data-redis/blob/2.7.13/src/main/java/org/springframework/data/redis/connection/lettuce/ClusterConnectionProvider.java#L83) a "`CompletableFuture`" (extending a `CompletionStage`) as the wrapper for the `RedisConnection` (technically, a Lettuce driver `StatefulRedisClusterConnection` instance in the "clustered" case, Lettuce `StatefulConnection` in the non-clustered case), then it should be possible to maybe pass in an `Exception` handler (`Function`) that release connection resources immediately when a connection fails on open. This, I could possible agree to. However, it does not excuse Spring Boot Actuator from handling the connection properly.

**Comment by jxblum** [comment]
Other factors to consider is:

1) Whether a "Pool" of connections has been configured, and...
2) Whether it is possible, or whether any `SocketOptions` have been supplied (indirectly) to the `LettuceClientConfiguration` (from [here](https://docs.spring.io/spring-data/redis/docs/2.7.12/api/org/springframework/data/redis/connection/lettuce/LettuceClientConfiguration.html#getClientOptions--) to [here](https://lettuce.io/core/release/api/io/lettuce/core/ClientOptions.html#getSocketOptions--)).

Typically, a (connection) "Pool" is responsible for acquiring and releasing connections along with there associated resources (TCP sockets, etc), even for "failed" connections, on "open" no less.

I'd almost argue that your Spring Boot (Data Redis) application should be failing-fast, particularly if the authentication criteria has not been properly specified and configured.  Why should the application even be allowed to start much less allow users to access the Spring Boot Actuator `HealthIndicator` for Redis to reveal anything?

Spring Data Redis does [offer and allow](https://docs.spring.io/spring-data/redis/docs/2.7.12/api/org/springframework/data/redis/connection/lettuce/LettuceConnectionFactory.html#getValidateConnection--) (disabled by default) validation of `RedisConnections` on startup.

**Comment by jxblum** [comment]
In any case, I want to get @mp911de or @christophstrobl's thought and opinions on this before we proceed with any changes to the framework.

**Comment by mp911de** [comment]
> if ClusterConnectionProvider.getConnection throw Exception, there maybe tcp connection leak

Do you have an example exception @970655147 that causes connection leaks for you?

**Comment by 970655147** [comment]
> leaks

Hello, reoccur like that 
new simple spring-boot project as follow 
1. pom.xml include spring-boot-starter-data-redis
`
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
`

2. application.yml config redis info, following config is mysql & kafka[just for test] 
`
spring:
  redis:
    cluster:
      nodes: "192.168.0.105:3306,192.168.0.105:9092"
    timeout: "PT3S"
`

3. add case code in Application of spring-boot 
`
package com.hx.boot;

import com.hx.boot.context.SpringContext;
import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.data.redis.connection.ReactiveRedisConnection;
import org.springframework.data.redis.connection.lettuce.LettuceConnectionFactory;
import org.springframework.scheduling.annotation.EnableAsync;

@EnableAsync
@MapperScan("com.hx.boot.mapper")
@SpringBootApplication
public class HelloSpringBootApplication implements CommandLineRunner {

    public static void main(String[] args) {
        SpringApplication.run(HelloSpringBootApplication.class, args);
    }

    @Override
    public void run(String... args) throws Exception {
        LettuceConnectionFactory factory = SpringContext.getBean(LettuceConnectionFactory.class);
        for (int i = 0; i < 100; i++) {
            try {
                ReactiveRedisConnection connection = factory.getReactiveConnection();
            } catch (Exception e) {
                // ignore
            }
        }
        int x = 0;
    }
}
`

4. watch leaks info 
`
root@ubuntu:~# ll /proc/5795/fd | grep 41
lrwx------ 1 root root 64 Jun 29 06:41 103 -> socket:[328474]
lrwx------ 1 root root 64 Jun 29 06:41 104 -> socket:[328475]
lrwx------ 1 root root 64 Jun 29 06:41 105 -> socket:[320448]
// ignore some file descriptor 
lrwx------ 1 root root 64 Jun 29 06:41 322 -> socket:[328586]
lrwx------ 1 root root 64 Jun 29 06:41 323 -> socket:[323163]
lrwx------ 1 root root 64 Jun 29 06:41 324 -> socket:[328587]
lrwx------ 1 root root 64 Jun 29 06:41 325 -> socket:[320477]
`



> > if ClusterConnectionProvider.getConnection throw Exception, there maybe tcp connection leak
> 
> Do you have an example exception @970655147 that causes connection leaks for you?

**Comment by jxblum** [comment]
@970655147 - First of all, you "ignored" the very thing (i.e. resulting "Exception") we [asked](https://github.com/spring-projects/spring-data-redis/issues/2619#issuecomment-1610971783) you to provide (in detail) in the first place:

```java
  // get connection
} catch (Exception e) {
            // ignore
}
```

> _"if ClusterConnectionProvider.getConnection throw Exception, there maybe tcp connection leak"_

What Exception?

By ignoring the Exception, you are implying any Exception, and it does not matter. But, it does! It does because it matters what happens during the "process" of opening the connection.

An Exception resulting from a username/password auth error is different from an Exception occurring because an incorrect IP address or port to the server was configured/resolved is different from an Exception thrown because of a failed TLS handshake (verification) during SSL/TLS identification & authentication (as described by [IBM](https://www.ibm.com/docs/en/ibm-mq/7.5?topic=ssl-how-tls-provide-authentication-confidentiality-integrity), for instance) is different from other TCP errors, and so on.

In the later case, as with username/password auth, a TCP connection is still established and therefore system resources will be allocated and used to complete the steps of the TLS handshake/verification (over SSL). After all, Secure Sockets, or a "secure" Socket, like `SSLSocket`, is nothing more than encrypted data over an otherwise "plaintext" `Socket` (i.e. data must be "encrypted" before it is sent over a `Socket`/network connection to be "secure"; there is no such thing as a hardware "secured" Socket; it is all "software").

This is also OS/system dependent.

As such, this why (TCP) Sockets have configuration (such as [SO_LINGER](https://docs.oracle.com/javase/8/docs/api/java/net/SocketOptions.html#SO_LINGER), among other `Socket` configuration [options](https://docs.oracle.com/javase/8/docs/api/java/net/SocketOptions.html), [timeouts](https://docs.oracle.com/javase/8/docs/api/java/net/SocketOptions.html#SO_TIMEOUT, reuse, etc).

Secondarily, this code:

```java
    LettuceConnectionFactory factory = SpringContext.getBean(LettuceConnectionFactory.class);
    for (int i = 0; i < 100; i++) {
        try {
            ReactiveRedisConnection connection = factory.getReactiveConnection();
...
..
.
```

Does not necessarily constitute a connection leak simply because an Exception might be thrown during an attempt to acquire a connection. You are simply iterating and opening connections without proper connection "handling". And, if it were unbounded, your problem would only exasberate the "perceived" problem.

Most file-based system resources (TCP Socket connections are no exception; see [here](https://en.wikipedia.org/wiki/Network_socket)), must be properly handled inside a block, such as following (using your example):

```java
    for (int i = 0; i < 100; i++) {
        try  (ReactiveRedisConnection connection = factory.getReactiveConnection()) {
        }
        catch (Exception cause) {
            // handle the exceptional condition appropriately; such as releasing/closing related resources and 
        }
```

Just because you attempt to establish a connection and 1) an Exception is thrown or 2) the block of code opening/using the connection falls out of scope, does not mean the framework, or any other facility for that matter, will automatically (or automagically) "close" the connection. And, even if "close" is called, it does not mean system resources will be immediately released (again, it depends on the Socket configuration using a factory when the Socket is created/opened).

It is always the user's responsibility to properly handle the connection, whether you are opening a Redis connection (regardless of type, e.g. Reactive), a (SQL) database connection (e.g. with JDBC), or simply opening a file. 

For example:

```java
try (FileReader fileReader = new FileReader(file)) {
    // do something with the "open" file
}
```

If not properly handled, there is no guarantee that systems resources (even in the file case) will be properly released. Again, mileage varies based on OS/system, among other factors.

Also see this [SO post](https://stackoverflow.com/questions/16814552/does-socket-error-mean-socket-is-closed) as further evidence to this case.

**Comment by jxblum** [comment]
1 last thing...

This is also why it is important to use some connection management facility, such as "pooling", which Spring Data Redis supports for both the Jedis and Lettuce drivers (see [here](https://docs.spring.io/spring-data/redis/docs/current/reference/html/#redis:connectors:connection)).

In addition, the closer you get to system controlled resources, like TCP connections, the more it matters what type of driver you are using, some which can be system dependent. It is also why certain drivers perform better or behave slightly differently on different platform, given no 2 things (like OSes) are completely equal in this regard.

**Comment by 970655147** [comment]
> @970655147 - First of all, you "ignored" the very thing (i.e. resulting "Exception") we [asked](https://github.com/spring-projects/spring-data-redis/issues/2619#issuecomment-1610971783) you to provide (in detail) in the first place:
> 
> ```java
>   // get connection
> } catch (Exception e) {
>             // ignore
> }
> ```
> 
> Regarding:
> 
> > _"if ClusterConnectionProvider.getConnection throw Exception, there maybe tcp connection leak"_
> 
> What Exception?
> 
> By ignoring the Exception, you are implying any Exception, and it does not matter. But, it does! It does because it matters what happens during the "process" of opening the connection.
> 
> An Exception resulting from a username/password auth error is different from an Exception occurring because an incorrect IP address or port to the server was configured/resolved is different from an Exception thrown because of a failed TLS handshake (verification) during SSL/TLS identification & authentication (as described by [IBM](https://www.ibm.com/docs/en/ibm-mq/7.5?topic=ssl-how-tls-provide-authentication-confidentiality-integrity), for instance) is different from other TCP errors, and so on.
> 
> In the later case, as with username/password-based auth, a TCP connection is still established and therefore system resources will be allocated and used to complete the steps of the TLS handshake/verification (over SSL/TLS). After all, Secure Sockets, or a "secure" Socket, like `SSLSocket`, is nothing more than encrypted data over an otherwise "plaintext" `Socket` (i.e. data must be "encrypted" before it is sent over a `Socket`/network connection to be "secure"; there is no such thing as a hardware "secured" Socket; it is all "software").
> 
> This is also OS/system dependent.
> 
> As such, this why (TCP) Sockets have configuration (such as [SO_LINGER](https://docs.oracle.com/javase/8/docs/api/java/net/SocketOptions.html#SO_LINGER), among other `Socket` configuration [options](https://docs.oracle.com/javase/8/docs/api/java/net/SocketOptions.html), [timeouts](https://docs.oracle.com/javase/8/docs/api/java/net/SocketOptions.html#SO_TIMEOUT), reuse, etc).
> 
> Secondarily, this code:
> 
> ```java
>     LettuceConnectionFactory factory = SpringContext.getBean(LettuceConnectionFactory.class);
>     for (int i = 0; i < 100; i++) {
>         try {
>             ReactiveRedisConnection connection = factory.getReactiveConnection();
> ...
> ..
> .
> ```
> 
> Does not necessarily constitute a connection leak simply because an Exception might be thrown during an attempt to acquire a connection. You are simply iterating and opening connections without proper connection "handling". And, if it were unbounded, your problem would only exasberate the "perceived" problem.
> 
> Most file-based system resources (TCP Socket connections are no exception; see [here](https://en.wikipedia.org/wiki/Network_socket)), must be properly handled inside a block, such as the following (using your example):
> 
> ```java
>     for (int i = 0; i < 100; i++) {
>         try  (ReactiveRedisConnection connection = factory.getReactiveConnection()) {
>         }
>         catch (Exception cause) {
>             // handle the exceptional condition appropriately; such as releasing/closing related resources and 
>         }
> ```
> 
> Just because you attempt to establish a connection and 1) an Exception is thrown or 2) the block of code opening/using the connection falls out of scope, does not mean the framework, or any other facility for that matter, will automatically (or automagically) "close" the connection. And, even if "close" is called, it does not mean system resources will be immediately released (again, it depends on the Socket configuration using a factory when the Socket is created/opened).
> 
> It is always the user's responsibility to properly handle the connection, whether you are opening a Redis connection (regardless of type, e.g. Reactive), a (SQL) database connection (e.g. with JDBC), or simply opening a file.
> 
> For example:
> 
> ```java
> try (FileReader fileReader = new FileReader(file)) {
>     // do something with the "open" file
> }
> ```
> 
> If not properly handled, there is no guarantee that systems resources (even in the file case) will be properly released. Again, mileage varies based on OS/system, among other factors.
> 
> Also see this [SO post](https://stackoverflow.com/questions/16814552/does-socket-error-mean-socket-is-closed) as further evidence to this case.


**following code based on spring-data-redis 2.0.5-RELEASE**

### 1. What Exception?
"Do you have an example exception", I have a wrong reading, I make sense of "example case"
exception as following, throw ex2 from lettuce, then spring-data-redis wrap ex1
```
ex1. getNativeConnection:964, LettuceConnectionFactory$SharedConnection (org.springframework.data.redis.connection.lettuce): "Unable to connect to Redis", and hold cause as follow
ex2. loadPartitions:790, RedisClusterClient (io.lettuce.core.cluster) - io.lettuce.core.RedisException: Cannot retrieve initial cluster partitions from initial URIs [RedisURI [host='192.168.0.106', port=3306], RedisURI [host='192.168.0.106', port=9092]]
```

### 2. with out exception handling on example case
my presentation is not imprecisely
"factory.getReactiveConnection();" throw ex, so I just ignore that for casualness

### 3. my first idea to proposal to spring-data-redis
the call stack trace in this case is like following
```
getConnection:55, ClusterConnectionProvider (org.springframework.data.redis.connection.lettuce)
getNativeConnection:957, LettuceConnectionFactory$SharedConnection (org.springframework.data.redis.connection.lettuce)
getConnection:932, LettuceConnectionFactory$SharedConnection (org.springframework.data.redis.connection.lettuce)
getSharedReactiveConnection:795, LettuceConnectionFactory (org.springframework.data.redis.connection.lettuce)
getReactiveConnection:329, LettuceConnectionFactory (org.springframework.data.redis.connection.lettuce)
```

if ex "Unable to connect to Redis" thrown from LettuceConnectionFactory$SharedConnection.getNativeConnection, so this.connection is always null
an in next, nextnext, .. call, it will connect to redis-server over and over again
```
LettuceConnectionFactory$SharedConnection.getConnection
StatefulConnection<E, E> getConnection() {
    synchronized (this.connectionMonitor) {
        if (this.connection == null) {
            this.connection = getNativeConnection();
        }
        if (getValidateConnection()) {
            validateConnection();
        }
        return this.connection;
    }
}
```

### 4. lettuce's RedisClusterClient.loadPartitions processing
I was wondering following processing handle
"getConnections(seed)" established connection, but "connections.close()" doesn't release that

loadPartitions:787, RedisClusterClient (io.lettuce.core.cluster)
```
public Map<RedisURI, Partitions> loadViews(Iterable<RedisURI> seed, boolean discovery) {
    long commandTimeoutNs = getCommandTimeoutNs(seed);
    Connections connections = null;
    try {
        connections = getConnections(seed).get(commandTimeoutNs, TimeUnit.NANOSECONDS);
        // ignore some code
        return nodeSpecificViews.toMap();
    } catch (InterruptedException e) {
        Thread.currentThread().interrupt();
        throw new RedisCommandInterruptedException(e);
    } finally {
        if (connections != null) {
            connections.close();
        }
    }
}
```

but I'm not sure, I'm not experienced, the "NioSocketChannel" is only increase without decrease
until "too many open files"
```
root@ubuntu:~# jmap -histo:live 6970 | grep NioSocketChannel
  38:           558          58032  io.netty.channel.socket.nio.NioSocketChannel
  66:           558          35712  io.netty.channel.socket.nio.NioSocketChannel$NioSocketChannelConfig
  99:           558          22320  io.netty.channel.socket.nio.NioSocketChannel$NioSocketChannelUnsafe
```

**Comment by jxblum** [comment]
Regarding **#3** above, and specifically, this statement:

> "_an in next, nextnext, .. call, it will connect to redis-server over and over again_"

_"What" will connect to redis-server over and over again?_

There is nothing in the call stack to which your refer that repeatedly (i.e. loops, and) attempts to establish a connection until (implied) successful (e.g. non-null).

Using Spring Data Redis `2.7.13`, you can navigate the call stack as follows (let's assume shared, clustered connections since you often refer to a "cluster"), then: 

> NOTE: Your line numbers do not line up. And, you somehow mixed clustered with non-clustered calls in your stack. This does not make sense. Never-the-less, it ultimately leads to a similar call stack since the difference between clustered and non-clustered depends on the Lettuce `RedisClient` configured and created when the `LettuceConnectionFactory` bean is "initialized".

[108](https://github.com/spring-projects/spring-data-redis/blob/2.7.13/src/main/java/org/springframework/data/redis/connection/lettuce/ClusterConnectionProvider.java#L108): `ClusterConnectionProvider.getConnectionAsyn(:Class)`
[53](https://github.com/spring-projects/spring-data-redis/blob/2.7.13/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnectionProvider.java#L53): `LettuceConnectionProvider.getConnection(:Class)`
[1383](https://github.com/spring-projects/spring-data-redis/blob/2.7.13/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnectionFactory.java#L1383): `LettuceConnectionFactory.SharedConnection.getNativeConnection()`
[1366](https://github.com/spring-projects/spring-data-redis/blob/2.7.13/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnectionFactory.java#L1366): `LettuceConnectionFactory.SharedConnection.getConnection()`
[1117](https://github.com/spring-projects/spring-data-redis/blob/2.7.13/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnectionFactory.java#L1117): `LettuceConnectionFactory.getSharedReactiveConnection()`
[529](https://github.com/spring-projects/spring-data-redis/blob/2.7.13/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnectionFactory.java#L529): `LettuceConnectionFactory.getReactiveClusterConnection()`
[505](https://github.com/spring-projects/spring-data-redis/blob/2.7.13/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnectionFactory.java#L505): `LettuceConnectionFactory.getReactiveConnection(..)`

If you are using "pooling" (highly **recommended** in this case), then the only difference would be an additional call between 1383 and 53, on line [97](https://github.com/spring-projects/spring-data-redis/blob/2.7.13/src/main/java/org/springframework/data/redis/connection/lettuce/LettucePoolingConnectionProvider.java#L97) in the `LettucePoolingConnectionProvider.getConnection(:Class)`.

> NOTE: A `LettucePoolingConnectonProvider` simply "wraps" the underlying, actualy `LettuceConnectionProvider`, such as the `ClusterConnectionProvider`, to "pool" connections. The pool configuration can also "limit" the number of connections so they do not grow unbounded.

In any case, his is very much dependent on the caller.

In your case, that would be the Spring Boot `RedisHealthIndicator`, which, TMK, is only triggered when you trip the URL endpoint exposed by Spring Boot Actuator to access the "health" of your Redis cluster (servers). There would need to be some "active" monitoring for the `RedisHealthIndicator` to repeatedly attempt to open connection and exhaust your "unbounded" (non-pooled) resources

Spring Data Redis cannot possibly know all the ways in which callers will attempt to acquire and use connections. Again, outside of `RedisTemplate` operations or Spring Data Redis _Repository_ infrastructure, which might acquire connections on the user's (or caller's) behalf, then if the caller or your application (client) code acquires a connection, it is the responsibility of the caller or your application logic to properly manage the connection.

You have 1 of 3 options, here:

1) Increase the hard and soft limits of your File Descriptors (FDs) in your Linus-based system. For [example](https://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/).

2) Configure and use connection pooling (**recommended**).

3) Fix your underlying Exception: `Cannot retrieve initial cluster partitions from initial URIs [RedisURI [host='192.168.0.106', port=3306], RedisURI [host='192.168.0.106', port=9092]]`.

I strongly encourage you to consider #2 and investigate #3. You clearly have misconfigured your environment in some way or have an some other (network) environment or Redis problem.
