### ISSUE TITLE
Specify redis template for the Repository

### ISSUE THREAD

**Issue by AlistratenkoNikita** [spring-projects/spring-data-redis#2648]
I have a few spring data repositories for redis. We are in middle of transition to new redis server. 
To make it smooth, I need to write data to the old and new redises simultaneously. So I need to have two sets of CRUD repositories in runtime, each of them should use different datasource (redis template). 
I've found an example to introduce a few datasources in Spring app, and use JPA. But I was wondering if it's possible to specify a datasource for the Spring data repository. 
Because I am not sure how I can make same operations I do with Repository (for first redis) using redis template (for second redis).
Thanks!

**Comment by jxblum** [comment]
@AlistratenkoNikita -

I assume you would (want to) use the same set of application-defined (Spring Data) _Repositories_ for both (old and new) Redis instances? That is, the application domain model being persisted by the _Repository_ definitions from your application did not change, and is the same for both Redis instances?

Out-of-the-box, Spring Data Redis, as well as most other Spring Data modules for that matter, do not support this type of arrangement when using Spring Data Repositories.

As you may know, Spring Data Redis's [Repository implementation](https://docs.spring.io/spring-data/redis/docs/current/reference/html/#redis.repositories) of the Spring Data (Commons) [Repository infrastructure](https://docs.spring.io/spring-data/commons/docs/current/reference/html/#repositories) uses a configured `RedisOperations` instance ([Javadoc](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/core/RedisOperations.html); backed by `RedisTemplate` (default)) under-the-hood to execute persistence operations (i.e. necessary Redis commands) for your application domain model objects (as identified in the _Repository_ definition) against the Redis instance. In turn, the `RedisOperations` instance uses a `RedisConnectionFactory` ([Javadoc](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/connection/RedisConnectionFactory.html)) to acquire connections in order to execute commands necessary to complete the Repository persistence operations on the configured Redis instance.

> NOTE: This pattern (Repository -> Template -> DataSource) is nearly identical for all Spring Data modules: JDBC, JPA, MongoDB, Neo4j, GemFire, Hazelcast, and so on.

Thus:

```txt
Redis Repository -> RedisOperations -> RedisConnectionFactory -> RedisConnection -> Redis command(s)
```

While it is possible to configure multiple Redis data sources (server(s), clusters) using Spring Data Redis, and even define templates (DAO) for each Redis instance required to be accessible from your application, for example:

```java
@Configuration
class ApplicationRedisConfiguration {

    @Bean("RedisOld")
    RedisConnectionFactory connectionFactoryToRedisOld(...) {
        // ...
    }

    @Bean("RedisNew")
    RedisConnectionFactory connectionFactoryToRedisNew(...) {
        // ...
    }

    @Bean
    RedisTemplate redisTemplateOld(@Qualifier("RedisOld") RedisConnectionFactory connectionFactory) {
        return newRedisTemplate(connectionFactory);
    }

    @Bean
    RedisTemplate redisTemplateNew(@Qualifier("RedisNew") RedisConnectionFactory connectionFactory) {
        return newRedisTemplate(connectionFactory);
    }

    private RedisTemplate newRedisTemplate(RedisConnectionFactory connectionFactory) {
        RedisTemplate template = new RedisTemplate();
        template.setConnectionFactory(connectionFactory);
        return template;
    }
}
```

> NOTE: See relevant sections in the Spring Data Redis reference documentation, [here](https://docs.spring.io/spring-data/redis/docs/current/reference/html/#redis:connectors) and [here](https://docs.spring.io/spring-data/redis/docs/current/reference/html/#redis:template).

And, even though you can configure the `RedisOperations` instance (i.e. `RedisTemplate`) used by your application-defined Repositories, for example:

```java
@Configuration
@EnableRedisRepositories(redisTemplateRef = "redisTemplateNew")
class ApplicationRedisConfiguration { 

    // connection, template and other bean definitions
}
```

It is not trivial to create multiple instances of the same application Repository definitions with different `RedisTemplate` instances backed by different (Redis) data sources (i.e. `RedisConnectionFactory` instances) using Spring Data (Redis)'s Repository Annotation-based configuration.

However...

It is possible, given `RedisOperations`  is an "_interface_" after all, to create a [_Composite_](https://en.wikipedia.org/wiki/Composite_pattern) template with _Composite_ operation interfaces as needed, defining the operations used by your Repository definitions.

For example (access modifiers and type parameters omitted):

```java
class CompositeRedisOperations implements RedisOperations {

    private final HashOperations compositeHashOperations;

    CompositeRedisOperations(@NonNull RedisOperations operationsOld, @NonNull RedisOperations operationsNew) {
        this.compositeHashOperations = new CompositeHashOperations(
            operationsOld.opsForHash(), 
            operationsNew.opsForHash());
    }

    HashOperations opsForHash() {
        return this.compositeHashOperations;
    }
    
    class CompositeHashOperations implements HashOperations {

        private final HashOperations hashOperationsOne;
        private final HashOperations hashOperationsTwo;

       CompositeHashOperations(@NonNull HashOperations hashOperationsOld,
            @NonNull HashOperations hashOperationsNew) {

            this.hashOperationsOld = hashOperationsOld;
            this.hashOperationsNew = hashOperationsNew;
        }

        Object get(Object key, Object hashKey) {
            // only read from new
            this.hashOperationsNew.get(key, hashKey);
        }

        void put(Object key, Object hashKey, Object value) {
            // write to both OLD and NEW Redis instances
            this.hashOperationsNew.put(key, hashKey, value);
            this.hashOperationsOld.put(key, hashKey, value);
        }

        // etc
}
```

Then:

```java
@Configuration
@EnableRedisRepositories(redisTemplateRef = "compositeRedisOperations")
class ApplicationRedisConfiguration {

    @Bean
    RedisOperations compositeRedisOperations(@Qualifier("redisTemplateOld") RedisTemplate templateOld, 
        @Qualifier("redisTemplateNew") RedisTemplate templateNew) {

        return new CompositeRedisOperations(templateOld, templateNew);
    }
}
```

There is obviously a bit of setup here, but it theoretically would work.

Although, I would caution you if you are using Reactive connections, Transactions, or other complex Redis operations (e.g. pub/sub) from your application. Basic CRUD or simple queries is one thing, but beyond this, you must plan carefully.

I don't even recommend this approach!

I present this just to demonstrate that it is possible and that Spring in general, generally allows users to configure and structure the applications however they deem necessary.

This approach will not be built in or supported by Spring Data Redis.

**Comment by jxblum** [comment]
Another approach involves the **programmatical** creation and configuration of Spring Data (Redis) Repository infrastructure components in your application, as documented [here](https://docs.spring.io/spring-data/commons/docs/current/reference/html/#repositories.create-instances.standalone).

However, this requires you to create and define a `RedisRepositoryFactoryBean` `@Bean` definition in your Spring application `@Configuration` class for every definition of your application-defined (extension of the) _Repository_ interface. You'd still end up with a "composite" approach, but would afford you more control over the configuration than the Annotation-based approach, thereby being able to customize each application Repository individually on creation.

Still, while it affords you more control, it won't save you from any less work; in fact, it is more work!

**Comment by jxblum** [comment]
The best approach, IMO, is to handle this in Redis itself, using some form of migration or conversion process, replicating between 2 different Redis instances.

Redis offers the [`MIGRATE` command](https://redis.io/commands/migrate/).

I am sure you can find other commercial offerings that replicate across separate Redis instances. However, I am not familiar with the offerings in this space. I'd refer to Redis, Inc. on this matter, personally.

Good luck!
