### ISSUE TITLE
Add support for spring.redis.sentinel.enabled=false

### ISSUE THREAD

**Issue by hamiltont** [spring-projects/spring-data-redis#2665]
Currently if sentinel properties are present in the default profile, no other spring profile can disable sentinel. Adding an explicit enabled property would allow backwards compatibility and also be consistent with multiple other spring projects. This would allow disabling sentinel in specific environments, such as during testing or in a non-HA environment. 

### Similar Examples

spring.data.jpa.repositories.enabled: Enables JPA repositories auto-configuration.
spring.data.mongodb.enabled: Enables MongoDB auto-configuration.
spring.data.redis.repositories.enabled: Enables Redis repositories auto-configuration.
spring.security.enabled: Enables Spring Security auto-configuration.
spring.sleuth.enabled: Enables Spring Cloud Sleuth for distributed tracing.
spring.batch.job.enabled: Enables Spring Batch job processing.
spring.jms.pub-sub-domain: Enables or disables the use of JMS pub-sub domain.
spring.jms.template.pub-sub-domain: Enables or disables the use of JMS pub-sub domain for the JmsTemplate.
spring.mail.enabled: Enables or disables the use of Spring Mail.
spring.webflux.enabled

## Details

As written `RedisSentinelConfiguration` and `RedisProperties` look for existence of `spring.redis.sentinel` to configure sentinel. Unfortunately [spring does not support setting null values](https://github.com/spring-projects/spring-framework/issues/19986), so  once these values exist they cannot be removed

## Example

In my specific use case, someone has setup this in `application.yml`

```
spring:
  redis:
    sentinel:
      master: ${REDIS_SENTINEL_MASTER_NAME}
      nodes: ${REDIS_SENTINEL_NODES_ADDRESS}
```

We are already using embedded redis to support mocking, but adding the following code to out `application-test.yml` does not stop sentinel from loading: 
```
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    sentinel:
      master: null
      nodes: null
```

## Specific Project Versions

```
[INFO] +- org.springframework.boot:spring-boot-starter-data-redis:jar:2.7.9:compile
[INFO] |  \- org.springframework.data:spring-data-redis:jar:2.7.8:compile
[INFO] |     +- org.springframework.data:spring-data-keyvalue:jar:2.7.8:compile
[INFO] |     +- org.springframework:spring-oxm:jar:5.3.25:compile
[INFO] |     \- org.springframework:spring-context-support:jar:5.3.25:compile
[INFO] +- redis.clients:jedis:jar:3.8.0:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.36:compile
```

**Comment by hamiltont** [comment]
## Workaround

Setup a manual configuration for loading the redisConnectionFactory that uses whatever settings you need. Example:  

```
/**
 * Generally we'd use @TestConfiguration, which needs an explicit @Import
 * annotation on each test classes to ensure proper segregation and control over
 * test-specific configurations. However there are no
 * sentinel-depended test at this time, so we just use @config to load this for all tests
 */
@Configuration
public class TestRedisConfiguration {

    /** Workaround for https://github.com/spring-projects/spring-data-redis/issues/2665 */
    @Bean
    @Primary
    public RedisConnectionFactory redisConnectionFactory() {
        return new JedisConnectionFactory();
    }
}
```

**Comment by jxblum** [comment]
First, your "_Similar Examples_" are not that similar at all. Each (Spring Boot) property applies to different aspects of Spring framework configuration and functionality.

Many of the properties you referenced (e.g. `spring.data.mongodb.enabled`, `spring.mail.enabled`, `spring.security.enabled`, `spring.sleuth.enabled`) are not even valid Spring Boot [properties](https://docs.spring.io/spring-boot/docs/2.7.9/reference/html/application-properties.html). I don't think they are even valid properties for the individual Spring projects (e.g. Spring Data MongoDB, Spring Security).

This is also apparent in the Spring Boot _auto-configuration_ class(es) for the configurable functionality (for example: [`MongoAutoConfiguration`](https://github.com/spring-projects/spring-boot/blob/v2.7.9/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/mongo/MongoAutoConfiguration.java#L49), nor [`MongoDataAutoConfiguration`](https://github.com/spring-projects/spring-boot/blob/v2.7.9/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/mongo/MongoDataAutoConfiguration.java#L54),  or [`MongoProperties`](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/mongo/MongoProperties.java#L41-L42) (i.e. no `enabled` field)).

In general, Spring Boot _auto-configuration_ is disabled (or enabled) as [documented](https://docs.spring.io/spring-boot/docs/current/reference/html/using.html#using.auto-configuration.disabling-specific) (i.e. via Annotation or the general `spring.autoconfigure.exclude` property).

Secondarily, you are not going to find conditional configuration for database connections (Redis, or otherwise) for different topology arrangements (e.g. Redis Cluster, or Redis Sentinel, etc) based on any configuration properties.

Lastly, if such properties were to exist, it would not be in Spring Data Redis. Even your references (an in particular, your declared application classpath) above, refer to Spring Boot.

**Comment by jxblum** [comment]
The Spring way to configure conditional Redis connections based on desired topology (e.g. [Redis Cluster](https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.data.spring.data.redis.cluster.max-redirects), or [Redis Sentinel](https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.data.spring.data.redis.sentinel.master)), which can have many different configuration parameters, is to use Spring Profiles, either profiled Spring Annotation-based configuration, or make use of profiled Spring Boot `application.properties` (see [docs](https://docs.spring.io/spring-boot/docs/2.7.9/reference/html/features.html#features.external-config.files.profile-specific)).

For example:

```java
@Profile("DEV")
@SpringBootConfiguration
class MyRedisDevelopmentConfiguration {


    @Bean
    RedisStandaloneConfiguration redisStandaloneConfiguration(RedisProperties redisProperties) {
        // ...
    }
}

@Profile("PROD")
@SpringBootConfiguration
class MyRedisProductionConfiguration {

    @Bean
    RedisSentinelConfiguration redisSentinelConfiguration(RedisProperties redisProperties) {
        // ...
    }
}
```

You can even combine the 2 `@Configuration` classes into 1, and use Spring Boot's `@ConditionalOnProperty(...)` annotation on the individual `@Bean` methods (see [Javadoc](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/condition/ConditionalOnProperty.html)).

Alternatively, you can create "profile-enabled" Spring Boot `application.properties` files. 

For example:

```properties
# Spring Boot application.properties for general Redis configuration

spring.data.redis.connect-timeout=...
...
```

```properties
# Spring Boot application-redis-standalone.properties for Redis standalone configuration

#spring.data.redis.url=... # alternatively to host & port
spring.data.redis.host=skullbox
spring.data.redis.port=6379
...
```

And:

```properties
# Spring Boot application-redis-sentinel.properties for Redis Sentinel topology configuration

spring.data.redis.sentinel.master=...
spring.data.redis.sentinel.nodes=...
spring.data.redis.sentinel.password=...
spring.data.redis.sentinel.username=...
...
```

Then, you can enable the desired Spring profile(s) using the `spring.profiles.active` property ([doc](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.profiles)) as a JVM System property of configure 1 more profiles in your Spring Boot application as [documented](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.profiles.adding-active-profiles).

For example: `spring.profiles.active=redis-sentinel`

Which will activate and apply the Spring Boot `application-redis-sentinel.properties`.
