### ISSUE TITLE
`Jsr310Converters` does not contain converters for `OffsetTime` and `OffsetDateTime`

### ISSUE THREAD

**Issue by DeltaIII** [spring-projects/spring-data-redis#2677]
When using `spring-data-redis` and `RedisSerializer.java()` I noticed that a field of type `OffsetTime` wasn't being serialised even though it implements `Serializable`. The root cause is that `SimpleTypeHolder` assumes that any class that starts with `java.time` is a simple type (which in turn means `CustomConversions.isSimpleType(OffsetTime.class) == true`). This breaks the assumption that `CustomConversions` has a converter for the type as per the javadoc:
> Returns whether the given type is considered to be simple. That means it's either a general simple type or we have a writing Converter registered for a particular type.

Expected behaviour:
- `customConversions.isSimpleType` returns false if there are no converters for `OffsetDateTime` or `OffsetTime`

Actual behaviour:
- `customConversions.isSimpleType(OffsetDateTime.class) == true` even if there are no converters for `OffsetDateTime` (and for `OffsetTime`

Relevant Code links:
https://github.com/spring-projects/spring-data-commons/blob/541f0ced32f3f8b2143ea5b793a489828567ff13/src/main/java/org/springframework/data/mapping/model/SimpleTypeHolder.java#L158

https://github.com/spring-projects/spring-data-commons/blob/541f0ced32f3f8b2143ea5b793a489828567ff13/src/main/java/org/springframework/data/convert/CustomConversions.java#L190

**Comment by mp911de** [comment]
I moved this ticket into Spring Data Redis as it is a module-specific concern. We have already quite a few [converters](https://github.com/spring-projects/spring-data-redis/blob/45621dd3ee8820286c43bb88b7b7697e9bb09e8b/src/main/java/org/springframework/data/redis/core/convert/Jsr310Converters.java#L44) for JSR-310 types, however we don't have ones for `Offset[Date]Time`.

Since you're a bit familiar with our code, do you want to submit a pull request so that we can ship a fix with the next release?

**Comment by jxblum** [comment]
FTR: I was able to produce a similar problem (I suppose) by simply adding a `OffsetDateTime` (persistent) property to the `Person` class from the [Spring Data Examples](https://github.com/spring-projects/spring-data-examples), Spring Data Redis [Repositories example](https://github.com/spring-projects/spring-data-examples/tree/main/redis/repositories), and setting a few `OffsetDateTime` values for the "_Starks_" (e.g. "_arya_").

Modified `Person` class:

```java
class Person {

    private OffsetDateTime lastAccessed;

    // other persistent properties

    Person lastAccessed(OffsetDateTime lastAccessed) {
        this.lastAccessed = lastAccessed;
        return this;
    }
}
```

Modified `PersonRepositoryTest` class:

```java
class PersonRepositoryTests {

    private Person arya = new Person("arya", "stark", Gender.FEMALE).lastAccessed(OffsetDateTime.now());

    // ...
}
```

Then I simply ran and debugged the `findBySingleProperty()` test case method.

I don't necessarily agree that we need "custom" SD `Converters` for `java.time` types, particularly since `java.time` types  are `java.io.Serializable`, and the Spring Data Redis `JdkSerializationRedisSerializer` (used by default in the `RedisTemplate`, which is used by the SD (Redis/KeyValue) Repository infrastructure) should be able serialize `OffsetDateTime` values to a `byte[]` for the persistent property to be mapped to Redis by the `MappingRedisConverter` and other supporting Repository infrastructure classes.

Of course, it would need to be given a chance to serialize and persist `java.time` values from persistent entities in the first place, but seemingly, the `MappingRedisConverter.writeToBucket(..)` [expects](https://github.com/spring-projects/spring-data-redis/blob/issue/2670/src/main/java/org/springframework/data/redis/core/convert/MappingRedisConverter.java#L778) there to be a registered, "custom" Conversion for a property of type `OffsetDateTime`.

The execution path for a persistent property of type `OffsetDateTime` on a persistent entity (such as the `Person` class in the examples), as witnessed from the debugger (with source references to Spring Data Redis (only), ignoring Spring Data KeyValue), follows:

0) `SimpleKeyValueRepository.save(entity)`

1) Calls SD KeyValue `KeyValueTemplate.insert(objectToInsert)`

2) [`RedisKeyValueTemplate.insert(id, objectToInsert)`](https://github.com/spring-projects/spring-data-redis/blob/3.1.2/src/main/java/org/springframework/data/redis/core/RedisKeyValueTemplate.java#L149)

3) Calls (back to) SD KeyValue `KeyValueTemplate.insert(id, objectToInsert)`

4) Calls [`RedisKeyValueAdapter.put(id, item, keyspace)`](https://github.com/spring-projects/spring-data-redis/blob/3.1.2/src/main/java/org/springframework/data/redis/core/RedisKeyValueAdapter.java#L195)

5) Calls [`MappingRedisConverter.write(source, sink:RedisData)`](https://github.com/spring-projects/spring-data-redis/blob/3.1.2/src/main/java/org/springframework/data/redis/core/convert/MappingRedisConverter.java#L426)

6) Calls [`MappingRedisConverter.writeInternal(..)`](https://github.com/spring-projects/spring-data-redis/blob/3.1.2/src/main/java/org/springframework/data/redis/core/convert/MappingRedisConverter.java#L668)

7) Then fails to write the `OffsetDateTime` since there is no registered, "custom" Conversion in [`MappingRedisConverter.writeToBucket(..)`](https://github.com/spring-projects/spring-data-redis/blob/3.1.2/src/main/java/org/springframework/data/redis/core/convert/MappingRedisConverter.java#L767-L801)

There should need to be a "custom" Conversion since the `OffsetDateTime`, or `java.time` types in general, are "simple" store types that can be serialized to a `byte[]` (by SD Redis's `JdkSerializationRedisSerializer`) and stored in the Redis has for a `Person` instance.

**Comment by jxblum** [comment]
On closer inspection, this may be a simple fix, by simply registering additional `java.time` `Converters` for `OffsetDateTime` and similar, missing `java.time` types, as necessary in SD Redis's `Jsr310Converters` class (see [here](https://github.com/spring-projects/spring-data-redis/blob/3.1.2/src/main/java/org/springframework/data/redis/core/convert/Jsr310Converters.java#L61-L76)).

**Comment by mp911de** [comment]
We never provided Zoned or Offset variants of temporal types on a broader basis because in typical stores working with dates, such a field requires two components (time, offset/zone) to be properly constructed without resorting to the system timezone.

In Redis, since everything is a byte array, we weren't asked to provide converters and so they never got added in the first place.

**Comment by lduffman** [comment]
Hi, I'm facing the same problem of serialisation of an OffsetDateTime. Is there any workaround using configuration with RedisCustomConversions or RedisTemplate ? Like many i tried to implement my proper RedisTemplate with its custom serializer (ObjectMapper with JavaTimeModule from jackson-datatype-jsr310 or my custom one) but never consumed on sending.

Here an example of the configuration i've done :

Configuration:

```
@Slf4j
@Configuration
public class CustomRedisConfiguration {

    @Bean
    public RedisConnectionFactory redisConnectionFactory() {
        var redisURI = RedisURI.builder()
                .withDatabase(0)
                .withHost("localhost")
                .withPort(6379)
                .build();
        RedisConfiguration redisConfiguration = LettuceConnectionFactory.createRedisConfiguration(redisURI);
        return new LettuceConnectionFactory(redisConfiguration);

    }

    @Bean
    public RedisCustomConversions redisCustomConversions(OffsetDateTimeToBytesConverter offsetToBytes) {
        return new RedisCustomConversions(Collections.singletonList(offsetToBytes));
    }

    @Primary
    @Bean
    RedisTemplate<String, TestOffsetDateTime> redisTemplate(RedisConnectionFactory connectionFactory) {
        RedisTemplate<String, TestOffsetDateTime> redisTemplate = new RedisTemplate<>();
        redisTemplate.setConnectionFactory(connectionFactory);
        redisTemplate.setKeySerializer(new StringRedisSerializer());
        redisTemplate.setValueSerializer(jackson2JsonRedisSerializer());
        redisTemplate.afterPropertiesSet();

        return redisTemplate;
    }
    @Bean
    public Jackson2JsonRedisSerializer<TestOffsetDateTime> jackson2JsonRedisSerializer() {
        var serializer =  new Jackson2JsonRedisSerializer<>(TestOffsetDateTime.class);
        ObjectMapper om = new ObjectMapper();
        om.disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);
        om.registerModule(new JavaTimeModule());
        om.registerModule(new SimpleModule().addSerializer(OffsetDateTime.class, new OffsetDateTimeSerializer()));
        serializer.setObjectMapper(om);

        return serializer;
    }
}
```

Serializer:
```
@Component
public class OffsetDateTimeSerializer extends JsonSerializer<OffsetDateTime> {
    private static final Logger log = LoggerFactory.getLogger(OffsetDateTimeSerializer.class);

    public OffsetDateTimeSerializer() {
    }

    public void serialize(OffsetDateTime offsetDateTime, JsonGenerator jsonGenerator, SerializerProvider serializerProvider) throws IOException {
        if (offsetDateTime == null) {
            throw new IOException("OffsetDateTime argument is null.");
        } else {
            log.info("LOG> in serializer {}", offsetDateTime);
            jsonGenerator.writeString(DateTimeFormatter.ISO_OFFSET_DATE_TIME.format(offsetDateTime));
        }
    }
}
```

Converter:
```
@Component
@WritingConverter
public class OffsetDateTimeToBytesConverter implements Converter<OffsetDateTime, byte[]> {
    @Override
    public byte[] convert(final OffsetDateTime source) {
        return source.format(DateTimeFormatter.ISO_OFFSET_DATE_TIME).getBytes();
    }
}
```

Object to send:
```
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class TestOffsetDateTime {

    public String string;
    @JsonFormat(
            shape = JsonFormat.Shape.STRING,
            pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"
    )
    public OffsetDateTime offsetDateTime;
    public LocalDateTime localDateTime;
    public Date date;
}
```

Publisher:
```
public RecordId test() {

        var test = TestOffsetDateTime.builder()
                .string("test")
                .localDateTime(LocalDateTime.now())
                .offsetDateTime(OffsetDateTime.now())
                .date(new Date())
                .build();

        ObjectRecord<String, TestOffsetDateTime> record = StreamRecords.newRecord()
                .ofObject(test)
                .withStreamKey("test-stream");

        RecordId r = this.redisOperations.opsForStream().add(record);
        log.info("LOG> recordId: {}", r);
        return r;
    }
```

**Comment by jxblum** [comment]
@mp911de - Then, I guess 1 question I have is, why are we de/serializing `ZonedDateTime`, [here](https://github.com/spring-projects/spring-data-redis/blob/3.1.2/src/main/java/org/springframework/data/redis/core/convert/Jsr310Converters.java#L67-L68)?

**Comment by mp911de** [comment]
Yeah, I would like to have these as well.
Am 16. Aug. 2023, 19:32 +0200 schrieb John Blum ***@***.***>:

**Comment by jxblum** [comment]
@DeltaIII & @lduffman -

I explored more on this issue today, and while Spring Data Redis currently does not support either `java.time.OffsetDateTime` or `java.time.OffsetTime` types presently, there is a workaround.

I have demonstrated this in my [redis-experiments](https://github.com/jxblum/redis-experiments) project, within the [spring-data-redis-experiments](https://github.com/jxblum/redis-experiments/tree/spring-data-redis-issue-2677/spring-data-redis-experiments) module, and specifically the [RedisRepositoryWithEntityHavingOffsetDateTimePropertyIntegrationTests](https://github.com/jxblum/redis-experiments/blob/spring-data-redis-issue-2677/spring-data-redis-experiments/src/test/java/io/vmware/spring/data/redis/tests/repository/RedisRepositoryWithEntityHavingOffsetDateTimePropertyIntegrationTests.java) class.

You can see that my `User` application entity type ([class](https://github.com/jxblum/redis-experiments/blob/spring-data-redis-issue-2677/spring-data-redis-experiments/src/test/java/io/vmware/spring/data/redis/tests/repository/RedisRepositoryWithEntityHavingOffsetDateTimePropertyIntegrationTests.java#L182-L209)) contains both a `OffsetDateTime` and `OffsetTime` properties ([here](https://github.com/jxblum/redis-experiments/blob/spring-data-redis-issue-2677/spring-data-redis-experiments/src/test/java/io/vmware/spring/data/redis/tests/repository/RedisRepositoryWithEntityHavingOffsetDateTimePropertyIntegrationTests.java#L191-L193)).

Additionally, I have "customized" the SD (Redis) _Repository_ infrastructure configuration, and specifically the "`RedisCustomConversions`" that is registered as a bean in the Spring `ApplicationContext` (container) when using the SD Redis _Repository_ infrastructure.

This allows you to add additional `Converters` required by your Spring (Boot) Data Redis applications.

First, I [defined](https://github.com/jxblum/redis-experiments/blob/spring-data-redis-issue-2677/spring-data-redis-experiments/src/test/java/io/vmware/spring/data/redis/tests/repository/RedisRepositoryWithEntityHavingOffsetDateTimePropertyIntegrationTests.java#L125-L180) custom `Converters` for the `java.time` types: `OffsetDateTime` and `OffsetTime`. This is not unlike how Spring Data Redis` Jsr310Converters` handles conversion for many of the `java.time` types already (see [here](https://github.com/spring-projects/spring-data-redis/blob/3.1.2/src/main/java/org/springframework/data/redis/core/convert/Jsr310Converters.java)).

Then, I simply replace the `RedisCustomConversions` bean with a new instance that registers all the provided converters in addition to my application-specific `Converters` using a Spring `BeanPostProcessor` (see [here](https://github.com/jxblum/redis-experiments/blob/spring-data-redis-issue-2677/spring-data-redis-experiments/src/test/java/io/vmware/spring/data/redis/tests/repository/RedisRepositoryWithEntityHavingOffsetDateTimePropertyIntegrationTests.java#L109-L123)).

**Comment by jxblum** [comment]
See #2681.

**Comment by DeltaIII** [comment]
Thank you very much 😄 

Any idea when this would be in a release?

**Comment by mp911de** [comment]
Check out the release calendar at https://calendar.spring.io/. As of now, the next round of releases is scheduled for tomorrow.
