### ISSUE TITLE
Dispose off not working for ClusterCommandExecutor 

### ISSUE THREAD

**Issue by vidushiguptaa** [spring-projects/spring-data-redis#2714]
Here in below code, clusterCommandExecutor is only destroyed if `disposeClusterCommandExecutorOnClose` is true
`public void close() throws DataAccessException {

		if (!isClosed() && disposeClusterCommandExecutorOnClose) {
			try {
				clusterCommandExecutor.destroy();
			} catch (Exception ex) {
				log.warn("Cannot properly close cluster command executor", ex);
			}
		}

		super.close();
	}`
	
But when getting the clusterConnection from JedisConnectionFactory or LettuceConnectionFactory, clusterConnection is created with `disposeClusterCommandExecutorOnClose = false` which is causing the resource leak
`protected LettuceClusterConnection(@Nullable StatefulRedisClusterConnection<byte[], byte[]> sharedConnection,
			LettuceConnectionProvider connectionProvider, ClusterTopologyProvider clusterTopologyProvider,
			ClusterCommandExecutor executor, Duration timeout) {

		super(sharedConnection, connectionProvider, timeout.toMillis(), 0);

		Assert.notNull(executor, "ClusterCommandExecutor must not be null.");

		this.topologyProvider = clusterTopologyProvider;
		this.clusterCommandExecutor = executor;
		this.disposeClusterCommandExecutorOnClose = false;
	}`

**Comment by jxblum** [comment]
What you fail to realize is, the `ClusterCommandExecutor` is not created by the connection classes in the case where the Jedis or Lettuce `RedisClusterConnection` constructors are "passed" an instance of `ClusterCommandExecutor` from the Jedis or Lettuce `RedisConnectionFactory`.

The difference for **Jedis** is [here](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterConnection.java#L108) and [here](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterConnection.java#L116-L118) vs. [here](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterConnection.java#L151-L152) and [here](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/connection/jedis/JedisClusterConnection.java#L162).

The difference in **Lettuce** is again [here](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceClusterConnection.java#L134) and [here](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceClusterConnection.java#L142-L144) vs. [here](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceClusterConnection.java#L168-L169) and [here](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceClusterConnection.java#L179).

This is true for all Jedis and Lettuce `RedisClusterConnection` constructors that accept a `ClusterCommandExecutor` as an argument.

Only when either the Jedis or Lettuce `RedisClusterConnection` class implicitly creates the `ClusterCommandExecutor` on the caller's behalf is the Jedis or Lettuce `RedisClusterConnection` appropriately responsible for the "**_lifecycle_**" of the `ClusterCommandExecutor`.

If the `ClusterCommandExecutor` is passed to the constructors as an external argument, then caller is responsible for the "**_lifecycle_**". This is because, potentially, the `ClusterCommandExecutor` could possibly be a "managed" bean declared and registered in the Spring container (`ApplicationContext`). After all, `ClusterCommandExecutor` [is a](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/connection/ClusterCommandExecutor.java#L49) `DisposableBean` (lifecycle bean) that will be properly [destroyed](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/connection/ClusterCommandExecutor.java#L343-L353) by the Spring container if managed as a bean.

For both the Jedis and Lettuce `RedisConnectionFactory` implementations, each creates connections by passing in the `ClusterCommandExecutor` created by the factories (for Jedis, see [here](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/connection/jedis/JedisConnectionFactory.java#L481); for Lettuce, see [here](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnectionFactory.java#L420-L421)).

This puts the `JedisConnectionFactory` and `LettuceConnectionFactory` solely in charge of the lifecycle for the `ClusterCommandExecutor` instance.

And, both `JedisConnectionFactory` as well as `LettuceConnectionFactory` appropriately release resources, too!

That is apparent in the `destroy()` lifecycle method of the `RedisConnectionFactory`. For Jedis, see [here](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/connection/jedis/JedisConnectionFactory.java#L442). For Lettuce, see [here](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnectionFactory.java#L351-L358).

Both [`JedisConnecionFactory`](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/connection/jedis/JedisConnectionFactory.java#L93) and [`LettuceConnectionFactory`](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/connection/lettuce/LettuceConnectionFactory.java#L107-L108) are Spring container lifecycle beans.

In addition, as the [documentation](https://docs.spring.io/spring-data/redis/docs/current/reference/html/#redis:connectors:connection) describes, both `JedisConnectionFactory` and `LettuceConnectionFactory` are created as "managed beans" in the Spring container.

Therefore, it is very unlikely that Spring Data Redis directly, or via Spring Boot, is creating a "resource leak".
