### ISSUE TITLE
Backport `GenericJackson2JsonRedisSerializer.configure(…)` to `3.1.x`

### ISSUE THREAD

**Issue by roeniss** [spring-projects/spring-data-redis#2722]
`GenericJackson2JsonRedisSerializer(ObjectMapper mapper)` constructor removes the chance to apply setup in `GenericJackson2JsonRedisSerializer(@Nullable String classPropertyTypeName)`. 

Currently I managed to make copy of `GenericJackson2JsonRedisSerializer.TypeResolverBuilder` like this:

```java
    @Bean
    GenericJackson2JsonRedisSerializer genericJackson2JsonRedisSerializer(ObjectMapper mapper) {
        GenericJackson2JsonRedisSerializer serializer = new GenericJackson2JsonRedisSerializer(mapper);
        GenericJackson2JsonRedisSerializer.registerNullValueSerializer(mapper, null);

        StdTypeResolverBuilder typer = new TypeResolverBuilder(DefaultTyping.EVERYTHING,
                mapper.getPolymorphicTypeValidator());
        typer = typer.init(JsonTypeInfo.Id.CLASS, null);
        typer = typer.inclusion(JsonTypeInfo.As.PROPERTY);
        
        if (StringUtils.hasText(classPropertyTypeName)) {
	        typer = typer.typeProperty(classPropertyTypeName);
        }
        mapper.setDefaultTyping(typer);

        return serializer;
    }

    private static class TypeResolverBuilder extends ObjectMapper.DefaultTypeResolverBuilder {
        // ... (same implementation with original)
    }
```

*original* in the comment means this: https://github.com/spring-projects/spring-data-redis/blob/main/src/main/java/org/springframework/data/redis/serializer/GenericJackson2JsonRedisSerializer.java#L381

I hope there's a more simple way to do this.

**Comment by jxblum** [comment]
From your code snippet above, it is not apparent what aspects of Jackson's `ObjectMapper` you customized. I assume you declared an object of type `ObjectMapper` as a managed bean in the Spring context? The question is, does the `ObjectMapper` instance really need to be managed by the Spring container?

> NOTE: There are other situations where Spring Data Redis's `GenericJackson2JsonRedisSerializer` creates and maintains separate and internal instances of `ObjectMapper`. For [example](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/serializer/GenericJackson2JsonRedisSerializer.java#L292-L293).

It is apparent that you are duplicating the logic from [this constructor](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/serializer/GenericJackson2JsonRedisSerializer.java#L93-L123), but are allowing the `ObjectMapper` to passed during construction, presumably because you constructed a "custom" instance of `ObjectMapper` as a managed bean in the Spring container.

You can accomplish this another way, if you do not need the `ObjectMapper` to strictly be a managed bean in the Spring context. 

> NOTE: For the record, is it questionable whether declaring an `ObjectMapper` as a managed bean is strictly necessary given customization are quite use case and/or domain specific.

Simply do the following:

```java
@Configuration
class MyApplicationRedisConfiguration {

    @Bean
    GenericJackson2JsonRedisSerializer jsonRedisSerializer(
            @Value("${spring.redis.serialization.class-property-type-name}") String classPropertyTypeName) {

        GenericJackson2JsonRedisSerializer jsonRedisSerializer = 
            new GenericJackson2JsonRedisSerializer(classPropertyTypeName);

        jsonRedisSerializer.configure(objectMapper -> {
            // add ObjectMapper customizations here
        });

        return jsonRedisSerializer;
    }
}
```

Additionally, your "jsonRedisSerializer" `@Bean` method could also be "injected" with other configuration used to customize the `ObjectMapper` created by Spring Data Redis's `GenericJackson2JsonRedisSerializer` (as seen [here](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/serializer/GenericJackson2JsonRedisSerializer.java#L108)).

I demonstrated such an injection with the `classPropertyTypeName` configuration. Clearly, you are able to add others.

**Comment by roeniss** [comment]
`configure` is the one that I need. Thank you jxblum! I'm using Spring bom 2.7.15 so I didn't notice such method exists (that method is added on 3.1.1 with this [PR](https://github.com/jxblum/spring-data-redis/commit/17820d1d52b624dccf053820726a63f6f6053ff8)).

> The question is, does the ObjectMapper instance really need to be managed by the Spring container? 
I needed not the one in spring container but one with jsr310 module added. When I debugged, objectmapper that is newly made in `GenericJackson2JsonRedisSerializer`  has only one module and Spring-managed objectmapper has 7 modules including jsr310 (for me, it is needed to serialize/deserialize Instant type). I had to use Spring's one or make one by meself. Either way need duplicating logic as you might guess.

**Comment by jxblum** [comment]
Hi @roeniss - Right, I was also wondering the version of the Spring (Boot/Data) BOM you had in play. Thank you for sharing that information. I always base my answers on the latest bits if not otherwise specified.

Anyway, I will talk to the team about potentially back porting this method (`configure(:Consumer<ObjectMapper>)`).

**Comment by roeniss** [comment]
Thank you so much! Farewell.

**Comment by jxblum** [comment]
@mp911de & @christophstrobl - I propose we (minimally) back port the `configure(:Consumer<ObjectMapper>)` method ([source](https://github.com/spring-projects/spring-data-redis/blob/3.1.4/src/main/java/org/springframework/data/redis/serializer/GenericJackson2JsonRedisSerializer.java#L257-L276) & [Javadoc](https://docs.spring.io/spring-data/redis/docs/current/api/org/springframework/data/redis/serializer/GenericJackson2JsonRedisSerializer.html#configure(java.util.function.Consumer))) I added to SD Redis to resolve Issue #2601, to `3.0.x` and `2.7.x`.

Thoughts?

**Comment by mp911de** [comment]
As this change (`GenericJackson2JsonRedisSerializer.configure(…)`) is already part of `3.1.x`, closing this issue.
