### ISSUE TITLE
Could data created by @Indexed automatically expired by @TimeToLive？

### ISSUE THREAD

**Issue by dzy5639313** [spring-projects/spring-data-redis#3001]
When data in redis expired by @TimeToLive, the secondary index data created by @Indexed never expired. 
Is it possible to set expire time of secondary index data with the same value as @TimeToLive？

**Comment by mp911de** [comment]
The indexes you refer to were created by Redis Repositories. Redis only supports top-level key TTLs (and since Redis 7.4 also Hash-field TTL). Any entries within a secondary index (set, geoset) cannot be expired by Redis itself.

To address this shortcoming, Spring Data Redis uses Pub/Sub listeners for keyspace events to remove expired elements from secondary indexes. That also means, if your application isn't running or has been disconnected from Redis, the secondary index cleanup isn't performed.

**Comment by dzy5639313** [comment]
> The indexes you refer to were created by Redis Repositories. Redis only supports top-level key TTLs (and since Redis 7.4 also Hash-field TTL). Any entries within a secondary index (set, geoset) cannot be expired by Redis itself.
> 
> To address this shortcoming, Spring Data Redis uses Pub/Sub listeners for keyspace events to remove expired elements from secondary indexes. That also means, if your application isn't running or has been disconnected from Redis, the secondary index cleanup isn't performed.

Does that mean that if I want to delete secondary index data, I need to implement the specific keyspace expire event listener myself?

**Comment by mp911de** [comment]
No, configuring your application with `@EnableRedisRepositories(enableKeyspaceEvents = ON_STARTUP)` is sufficient.

**Comment by dzy5639313** [comment]
> No, configuring your application with `@EnableRedisRepositories(enableKeyspaceEvents = ON_STARTUP)` is sufficient.

thanks!

**Comment by nandorholozsnyak** [comment]
Sorry for bothering, the fact that enabling the keyspace event listener will do its job, but it won't work on GCP MemoryStore as the CONFIG command is forbidden.
Is there any other solution for that? I guess it will be an issue to handle that and make sure the event listener starts in this case as well if there is any error during reading the config parameter.
