### ISSUE TITLE
[Lettuce] Externalize ReadFrom configuration into property

### ISSUE THREAD

**Issue by thiagoteichmann** [spring-projects/spring-data-redis#3011]
Currently using Lettuce but noticed that  config properties lacks readFrom property and require code change to implement it, would be possible to externalize this in a property so we can override the default?

I currently have a redis sentinel totally configured by properties but I cannot configure read from property the same way.

Something like:
```
spring.redis.lettuce.config.read-from=REPLICA_PREFERRED

or 

spring.redis.config.read-from=REPLICA_PREFERRED
```

**Comment by mp911de** [comment]
This is a Spring Boot issue, please file a ticket at https://github.com/spring-projects/spring-boot/issues.

**Comment by thiagoteichmann** [comment]
Can you clarify why is not a spring data redis @mp911de ?

**Comment by mp911de** [comment]
Because Spring Boot hosts the code to parse config properties and apply these to `LettuceConnectionFactory` and its config. See https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/data/redis/LettuceConnectionConfiguration.java

**Comment by thiagoteichmann** [comment]
Thanks @mp911de !
